<?php

use App\Models\Acesso;
use App\Models\Funcao;
use App\Models\Permissao;
use Illuminate\Database\Seeder;

class AcessoSeeder extends Seeder
{
    /**
     * Adiciona as permissões informadas na função
     *
     * @param Funcao $job
     * @param string[] $permissions
     * @return void
     */
    public function apply($job, $permissions)
    {
        foreach ($permissions as $name) {
            $permition = Permissao::where('nome', $name)->firstOrFail();
            (new Acesso([
                'funcao_id' => $job->id,
                'permissao_id' => $permition->id,
            ]))->save();
        }
    }

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $admin = Funcao::where('descricao', __('messages.administrator'))->first();
        $this->apply($admin, [
            'acesso:create',
            'acesso:delete',
            'acesso:view',
            'associacao:update',
            'associacao:view',
            'auditoria:view',
            'avaliacao:update',
            'avaliacao:view',
            'bairro:create',
            'bairro:delete',
            'bairro:update',
            'bairro:view',
            'banco:create',
            'banco:delete',
            'banco:update',
            'banco:view',
            'caixa:create',
            'caixa:delete',
            'caixa:reopen',
            'caixa:update',
            'caixa:view',
            'cardapio:create',
            'cardapio:delete',
            'cardapio:update',
            'cartao:create',
            'cartao:delete',
            'cartao:update',
            'cartao:view',
            'carteira:create',
            'carteira:delete',
            'carteira:update',
            'carteira:view',
            'catalogo:create',
            'catalogo:delete',
            'catalogo:update',
            'catalogo:view',
            'categoria:create',
            'categoria:delete',
            'categoria:update',
            'categoria:view',
            'cheque:update',
            'cheque:view',
            'cidade:create',
            'cidade:delete',
            'cidade:update',
            'cidade:view',
            'classificacao:create',
            'classificacao:delete',
            'classificacao:update',
            'classificacao:view',
            'cliente:create',
            'cliente:delete',
            'cliente:update',
            'cliente:view',
            'comanda:create',
            'comanda:delete',
            'comanda:update',
            'comanda:view',
            'composicao:create',
            'composicao:delete',
            'composicao:update',
            'compra:create',
            'compra:delete',
            'compra:update',
            'compra:view',
            'conta:create',
            'conta:delete',
            'conta:update',
            'conta:view',
            'contagem:view',
            'cozinha:create',
            'cozinha:delete',
            'cozinha:update',
            'cozinha:view',
            'credito:cancel',
            'credito:create',
            'credito:update',
            'credito:view',
            'cupom:create',
            'cupom:delete',
            'cupom:update',
            'cupom:view',
            'dispositivo:create',
            'dispositivo:delete',
            'dispositivo:update',
            'dispositivo:validate',
            'dispositivo:view',
            'emitente:update',
            'emitente:view',
            'empresa:update',
            'empresa:view',
            'estado:create',
            'estado:delete',
            'estado:update',
            'estado:view',
            'estoque:cancel',
            'estoque:create',
            'estoque:update',
            'estoque:view',
            'evento:view',
            'forma:create',
            'forma:delete',
            'forma:update',
            'forma:view',
            'funcao:create',
            'funcao:delete',
            'funcao:update',
            'funcao:view',
            'grupo:create',
            'grupo:delete',
            'grupo:update',
            'horario:create',
            'horario:delete',
            'horario:update',
            'horario:view',
            'imposto:create',
            'imposto:delete',
            'imposto:update',
            'imposto:view',
            'impressora:create',
            'impressora:delete',
            'impressora:update',
            'impressora:view',
            'integracao:update',
            'integracao:view',
            'item:cancel',
            'item:prepare',
            'item:view',
            'juncao:create',
            'juncao:update',
            'juncao:view',
            'lista:create',
            'lista:delete',
            'lista:update',
            'lista:view',
            'mesa:create',
            'mesa:delete',
            'mesa:update',
            'mesa:view',
            'metrica:create',
            'metrica:delete',
            'metrica:update',
            'metrica:view',
            'modulo:update',
            'modulo:view',
            'moeda:create',
            'moeda:delete',
            'moeda:update',
            'moeda:view',
            'movimentacao:create',
            'movimentacao:update',
            'movimentacao:view',
            'nota:cancel',
            'nota:create',
            'nota:update',
            'nota:view',
            'operacao:create',
            'operacao:delete',
            'operacao:update',
            'operacao:view',
            'origem:create',
            'origem:delete',
            'origem:update',
            'origem:view',
            'pacote:create',
            'pacote:delete',
            'pacote:update',
            'pagamento:update',
            'pagamento:view',
            'pais:create',
            'pais:delete',
            'pais:update',
            'pais:view',
            'pedido:cancel',
            'pedido:create',
            'pedido:type:card',
            'pedido:type:counter',
            'pedido:type:delivery',
            'pedido:type:table',
            'pedido:update',
            'pedido:view',
            'prestador:create',
            'prestador:delete',
            'prestador:update',
            'prestador:view',
            'produto:create',
            'produto:delete',
            'produto:update',
            'produto:view',
            'promocao:create',
            'promocao:delete',
            'promocao:update',
            'propriedade:create',
            'propriedade:delete',
            'propriedade:update',
            'regime:create',
            'regime:delete',
            'regime:update',
            'regime:view',
            'requisito:create',
            'requisito:delete',
            'requisito:update',
            'requisito:view',
            'resumo:create',
            'resumo:update',
            'resumo:view',
            'saldo:view',
            'servico:create',
            'servico:delete',
            'servico:update',
            'servico:view',
            'sessao:view',
            'setor:create',
            'setor:delete',
            'setor:update',
            'setor:view',
            'sistema:update',
            'sistema:view',
            'tributacao:create',
            'tributacao:delete',
            'tributacao:update',
            'tributacao:view',
            'unidade:create',
            'unidade:delete',
            'unidade:update',
            'unidade:view',
            'viagem:create',
            'viagem:delete',
            'viagem:update',
            'viagem:view',
            'zona:create',
            'zona:delete',
            'zona:update',
            'zona:view',
        ]);
        $waiter = Funcao::where('descricao', __('messages.waiter'))->first();
        $this->apply($waiter, [
            'mesa:view',
            'comanda:view',
            'estado:view',
            'cidade:view',
            'pais:view',
        ]);
        $cash_operator = Funcao::where('descricao', __('messages.cash_operator'))->first();
        $this->apply($cash_operator, [
            'categoria:create',
            'categoria:delete',
            'categoria:view',
            'cidade:create',
            'cidade:update',
            'cidade:view',
            'comanda:delete',
            'comanda:view',
            'estado:view',
            'forma:create',
            'forma:view',
            'mesa:create',
            'mesa:delete',
            'mesa:view',
            'moeda:create',
            'moeda:delete',
            'moeda:update',
            'pais:update',
            'pais:view',
            'pedido:update',
            'pedido:view',
            'prestador:create',
            'prestador:delete',
            'prestador:update',
            'prestador:view',
            'sessao:view',
            'setor:delete',
            'setor:view',
            'viagem:update',
        ]);
        $cooker = Funcao::where('descricao', __('messages.cooker'))->first();
        $this->apply($cooker, [
            'setor:view',
        ]);
        $deliveryman = Funcao::where('descricao', __('messages.deliveryman'))->first();
        $this->apply($deliveryman, [
            'categoria:update',
            'moeda:view',
            'prestador:create',
            'setor:view',
            'zona:view',
        ]);
        $stockist = Funcao::where('descricao', __('messages.stockist'))->first();
        $this->apply($stockist, [
            'cartao:view',
            'carteira:view',
            'categoria:delete',
            'forma:delete',
            'integracao:view',
            'setor:view',
            'viagem:delete',
            'zona:create',
        ]);
    }
}
