version: '2'
services:
    web:
        image: nginx
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/nginx/location.info:/etc/nginx/conf.d/location.info"
            - "./:/var/www/html"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
            - "./etc/nginx/location.template.conf:/etc/nginx/conf.d/location.template"
        ports:
            - "${WEB_PORT}:80"
        environment:
            - WEB_HOST=${WEB_HOST}
            - FASTCGI_HOST=${FASTCGI_HOST}
            - FASTCGI_PORT=${FASTCGI_PORT}
            - PROXY_HOST=${PROXY_HOST}
            - PUBLIC_PATH=${PUBLIC_PATH}
        command: /bin/bash -c "envsubst '$$WEB_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && envsubst '$$FASTCGI_HOST $$FASTCGI_PORT $$PROXY_HOST $$PUBLIC_PATH' < /etc/nginx/conf.d/location.template > /etc/nginx/conf.d/location.info && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - db
    php:
        image: nanoninja/php-fpm:7.1
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./:/var/www/html"
    composer:
        image: "composer"
        volumes:
            - "./:/app"
        command: install
    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "${ADMIN_PORT}:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=db
            - PMA_USER=${DB_USER}
            - PMA_PASSWORD=${DB_PASSWORD}
        restart: always
        depends_on:
            - db
    db:
        image: mysql:5.6
        command: mysqld --wait_timeout=2147483 --max_allowed_packet=50M --character-set-server=latin1 --default-storage-engine=INNODB --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" --max_connections=300 --innodb_use_native_aio=0
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - "${DB_EXTERNAL_PORT}:${DB_PORT}"
        volumes:
            - "./storage/db/mysql:/var/lib/mysql"