mutation updateConta(
  $id: ID!
  $input: ContaUpdateInput!
  $desagrupar: Boolean
) {
  UpdateConta(id: $id, input: $input, desagrupar: $desagrupar) {
    id
    descricao
    valor
    vencimento
    data_emissao
    estado
  }
}
