mutation updateConta($id: ID!, $input: ContaUpdateInput!, $recursive: Boolean) {
  UpdateConta(id: $id, input: $input, recursive: $recursive) {
    id
    descricao
    valor
    vencimento
    data_emissao
    estado
  }
}
