<?php
use Symfony\Component\Routing\RouteCollection;

$main_collection = new RouteCollection();

\MZ\System\PaginaPageController::addRoutes($main_collection);

$main_collection->addCollection(require_once(__DIR__ . '/api.php'));
$main_collection->addCollection(require_once(__DIR__ . '/old_api.php'));

\MZ\Environment\MesaPageController::addRoutes($main_collection);
\MZ\Session\SessaoPageController::addRoutes($main_collection);
\MZ\Session\CaixaPageController::addRoutes($main_collection);
\MZ\Wallet\BancoPageController::addRoutes($main_collection);
\MZ\Wallet\CarteiraPageController::addRoutes($main_collection);
\MZ\Payment\FormaPagtoPageController::addRoutes($main_collection);
\MZ\Payment\CartaoPageController::addRoutes($main_collection);
\MZ\Employee\FuncaoPageController::addRoutes($main_collection);
\MZ\Account\ClientePageController::addRoutes($main_collection);
\MZ\Employee\FuncionarioPageController::addRoutes($main_collection);
\MZ\Wallet\MoedaPageController::addRoutes($main_collection);
\MZ\Location\PaisPageController::addRoutes($main_collection);
\MZ\Location\EstadoPageController::addRoutes($main_collection);
\MZ\Location\CidadePageController::addRoutes($main_collection);
\MZ\Location\BairroPageController::addRoutes($main_collection);
\MZ\Location\LocalizacaoPageController::addRoutes($main_collection);
\MZ\Sale\ComandaPageController::addRoutes($main_collection);
\MZ\Session\MovimentacaoPageController::addRoutes($main_collection);
\MZ\Sale\PedidoPageController::addRoutes($main_collection);
\MZ\Product\CategoriaPageController::addRoutes($main_collection);
\MZ\Product\UnidadePageController::addRoutes($main_collection);
\MZ\Environment\SetorPageController::addRoutes($main_collection);
\MZ\Invoice\OrigemPageController::addRoutes($main_collection);
\MZ\Invoice\OperacaoPageController::addRoutes($main_collection);
\MZ\Invoice\ImpostoPageController::addRoutes($main_collection);
\MZ\Invoice\TributacaoPageController::addRoutes($main_collection);
\MZ\Product\ProdutoPageController::addRoutes($main_collection);
\MZ\Product\ServicoPageController::addRoutes($main_collection);
\MZ\Sale\ProdutoPedidoPageController::addRoutes($main_collection);
\MZ\Payment\ChequePageController::addRoutes($main_collection);
\MZ\Account\ClassificacaoPageController::addRoutes($main_collection);
\MZ\Account\ContaPageController::addRoutes($main_collection);
\MZ\Account\CreditoPageController::addRoutes($main_collection);
\MZ\Payment\PagamentoPageController::addRoutes($main_collection);
\MZ\System\AuditoriaPageController::addRoutes($main_collection);
\MZ\Payment\FolhaChequePageController::addRoutes($main_collection);
\MZ\Product\ComposicaoPageController::addRoutes($main_collection);
\MZ\Stock\FornecedorPageController::addRoutes($main_collection);
\MZ\Stock\EstoquePageController::addRoutes($main_collection);
\MZ\Product\GrupoPageController::addRoutes($main_collection);
\MZ\Product\PropriedadePageController::addRoutes($main_collection);
\MZ\Product\PacotePageController::addRoutes($main_collection);
\MZ\Device\DispositivoPageController::addRoutes($main_collection);
\MZ\Device\ImpressoraPageController::addRoutes($main_collection);
\MZ\Sale\PromocaoPageController::addRoutes($main_collection);
\MZ\System\FuncionalidadePageController::addRoutes($main_collection);
\MZ\System\PermissaoPageController::addRoutes($main_collection);
\MZ\Employee\AcessoPageController::addRoutes($main_collection);
\MZ\Stock\CatalogoPageController::addRoutes($main_collection);
\MZ\System\SistemaPageController::addRoutes($main_collection);
\MZ\Product\InformacaoPageController::addRoutes($main_collection);
\MZ\Session\ResumoPageController::addRoutes($main_collection);
\MZ\Sale\FormacaoPageController::addRoutes($main_collection);
\MZ\Stock\ListaPageController::addRoutes($main_collection);
\MZ\System\ModuloPageController::addRoutes($main_collection);
\MZ\Stock\CompraPageController::addRoutes($main_collection);
\MZ\Stock\RequisitoPageController::addRoutes($main_collection);
\MZ\Location\EnderecoPageController::addRoutes($main_collection);
\MZ\Company\HorarioPageController::addRoutes($main_collection);
\MZ\Product\ValorNutricionalPageController::addRoutes($main_collection);
\MZ\Sale\TransferenciaPageController::addRoutes($main_collection);
\MZ\Environment\PatrimonioPageController::addRoutes($main_collection);
\MZ\Sale\JuncaoPageController::addRoutes($main_collection);
\MZ\Invoice\RegimePageController::addRoutes($main_collection);
\MZ\Invoice\EmitentePageController::addRoutes($main_collection);
\MZ\Invoice\NotaPageController::addRoutes($main_collection);
\MZ\Invoice\EventoPageController::addRoutes($main_collection);
\MZ\System\IntegracaoPageController::addRoutes($main_collection);

return $main_collection;
