SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

USE `GrandChef`;

INSERT INTO `Servidores` (`ID`, `GUID`) VALUES
	(1, UUID());

INSERT INTO `Sistema` (`ID`, `ServidorID`, `VersaoDB`, `UltimoBackup`, `Dispositivos`) VALUES
	('1', 1, "2.0.0.0", NOW(), 1);

INSERT INTO `Moedas` (`ID`, `Nome`, `Simbolo`, `Codigo`, `Divisao`, `Fracao`, `Formato`, `Ativa`) VALUES
	(1, "Real", "R$", "BRL", 100, "Centavo", "R$ %s", 'Y'),
	(2, "Dollar", "$", "USD", 100, "Cent", "$ %s", 'N'),
	(3, "Euro", "€", "EUR", 100, "Cent", "€ %s", 'N'),
	(4, "Metical", "MT", "MZN", 100, "Centavo", "%s MT", 'N');

INSERT INTO `Paises` (`ID`, `Nome`, `Sigla`, `Codigo`, `MoedaID`, `Idioma`, `Entradas`, `Unitario`) VALUES
	(1, "Brasil", "BRA", "BR", 1, 'pt-BR', NULL, 'N'),
	(2, "United States of America", "USA", "US", 2, 'en-US', 'W1RpdHVsb10NCkNFUD1aSVANCkNQRj1TU04NCg0KW01hc2NhcmFdDQpDRVA9OTk5OTkNCkNQRj05OTktOTktOTk5OQ0KVGVsZWZvbmU9KDk5OSkgOTk5LTk5OTkNCg0KW0F1ZGl0b3JpYV0NCg0K', 'N'),
	(3, "España", "ESP", "ES", 3, 'es-ES', 'W1RpdHVsb10NCkNOUEo9UlVUDQpDUEY9TlVJUA0KQ0VQPUNPUA0KDQpbTWFzY2FyYV0NCkNQRj05Ljk5OS45OTkuOTk5DQpDRVA9OTk5OTkNCkNOUEo9OTkuOTk5Ljk5OS05DQpUZWxlZm9uZT05OTkgOTk5IDk5OQ0KDQo=', 'Y'),
	(4, "Moçambique", "MOZ", "MZ", 4, 'pt-BR', 'W1RpdHVsb10NCkNOUEo9TlVJVA0KQ0VQPUNPUA0KDQpbTWFzY2FyYV0NCkNOUEo9OS45OTk5OTk5LTkNCkNFUD05OTk5DQpUZWxlZm9uZT05OTk5LTk5OTk5DQoNCg==', 'Y');

INSERT INTO `Estados` (`ID`, `PaisID`, `Nome`, `UF`) VALUES
	(1, 2, "Alaska", "AK"),
	(2, 2, "Alabama", "AL"),
	(3, 2, "Arkansas", "AR"),
	(4, 2, "Arizona", "AZ"),
	(5, 2, "California", "CA"),
	(6, 2, "Colorado", "CO"),
	(7, 2, "Connecticut", "CT"),
	(8, 2, "Delaware", "DE"),
	(9, 2, "Florida", "FL"),
	(10, 2, "Georgia", "GA"),
	(11, 2, "Hawaii", "HI"),
	(12, 2, "Iowa", "IA"),
	(13, 2, "Idaho", "ID"),
	(14, 2, "Illinois", "IL"),
	(15, 2, "Indiana", "IN"),
	(16, 2, "Kansas", "KS"),
	(17, 2, "Kentucky", "KY"),
	(18, 2, "Louisiana", "LA"),
	(19, 2, "Massachusetts", "MA"),
	(20, 2, "Maryland", "MD"),
	(21, 2, "Maine", "ME"),
	(22, 2, "Michigan", "MI"),
	(23, 2, "Minnesota", "MN"),
	(24, 2, "Missouri", "MO"),
	(25, 2, "Mississippi", "MS"),
	(26, 2, "Montana", "MT"),
	(27, 2, "North Carolina", "NC"),
	(28, 2, "North Dakota", "ND"),
	(29, 2, "Nebraska", "NE"),
	(30, 2, "New Hampshire", "NH"),
	(31, 2, "New Jersey", "NJ"),
	(32, 2, "New Mexico", "NM"),
	(33, 2, "Nevada", "NV"),
	(34, 2, "New York", "NY"),
	(35, 2, "Ohio", "OH"),
	(36, 2, "Oklahoma", "OK"),
	(37, 2, "Oregon", "OR"),
	(38, 2, "Pennsylvania", "PA"),
	(39, 2, "Rhode Island", "RI"),
	(40, 2, "South Carolina", "SC"),
	(41, 2, "South Dakota", "SD"),
	(42, 2, "Tennessee", "TN"),
	(43, 2, "Texas", "TX"),
	(44, 2, "Utah", "UT"),
	(45, 2, "Virginia", "VA"),
	(46, 2, "Vermont", "VT"),
	(47, 2, "Washington", "WA"),
	(48, 2, "Wisconsin", "WI"),
	(49, 2, "West Virginia", "WV"),
	(50, 2, "Wyoming", "WY"),
	(51, 2, "District of Columbia", "DC");

INSERT INTO `Funcoes` (`ID`, `Descricao`, `Remuneracao`) VALUES
	(1, "Administrator", 1400),
	(2, "Waiter", 880),
	(3, "Checkout Operator", 1200),
	(4, "Cook", 880),
	(5, "Caretaker", 880),
	(6, "Deliveryman", 880),
	(7, "Stockist", 880);

INSERT INTO `Modulos` (`ID`, `Nome`, `Descricao`, `Habilitado`) VALUES
	(1, "Tables", "Lets make sales tables", 'Y'),
	(2, "Point of Sale", "It allows you to perform quick sales with barcode", 'Y'),
	(3, "Consumption Card", "Lets make sales with consumer card", 'Y'),
	(4, "Delivery", "Lets make sales for delivery", 'Y'),
	(5, "Stock", "It allows you to control stock with supplier registration", 'Y'),
	(6, "Account control", "It allows registering accounts payable and receivable", 'Y'),
	(7, "Eletronic command", "Lets you make orders from phone or tablet", 'Y');

INSERT INTO `Funcionalidades` (`ID`, `Nome`, `Descricao`) VALUES
	(1, "Operational", "Controls operations in system screens"),
	(2, "Sales", "Controls cancellations and other sales operations"),
	(3, "Tables and Cards", "Manages operations on tables and commanding"),
	(4, "Financial", "Control boxes and requests for payment"),
	(5, "Stock", "Controls access to inventory management"),
	(6, "Register", "It allows access to the screen of entries"),
	(7, "Report", "Controls viewing or reporting"),
	(8, "System", "Control devices and system behavior");

INSERT INTO `Permissoes` (`ID`, `FuncionalidadeID`, `Nome`, `Descricao`) VALUES
	(1, 1, "Sistema", "Allow access to the system"),
	(2, 8, "Restauracao", "Allow restore the database"),
	(3, 8, "Backup", "Allow performing database backup"),
	(4, 2, "PedidoMesa", "Allow place orders for a table"),
	(5, 2, "Pagamento", "Allow make a payment and make quick sales"),
	(6, 3, "MudarDeMesa", "Allow change requests from one table to another"),
	(7, 2, "ExcluirPedido", "Allow cancel products of an application"),
	(8, 3, "ReservarMesa", "Allow to reserve a table"),
	(9, 3, "LiberarMesa", "Allow free table reserved by another employee"),
	(10, 4, "SelecionarCaixa", "Allow select another open box"),
	(11, 4, "AbrirCaixa", "Allow open the box"),
	(12, 4, "InserirNoCaixa", "Allow insert money in the box"),
	(13, 4, "RetirarDoCaixa", "Allow withdraw cash box"),
	(14, 4, "FecharCaixa", "Allow close any open box"),
	(15, 3, "AlterarPreco", "Allow change the price of a product at the time of sale"),
	(16, 3, "Mesas", "Allow access for sale for all tables"),
	(17, 5, "Estoque", "Allow to entry of products in stock"),
	(18, 8, "OpcoesImpressao", "Allow change the report printing options"),
	(19, 8, "TrocarPlano", "Allow change application background"),
	(20, 8, "ModoTela", "Allow change the application screen mode"),
	(21, 7, "RelatorioVendas", "Allow all the sales"),
	(22, 7, "RelatorioVendedor", "Allow view the total sales for all vendors"),
	(23, 7, "RelatorioCaixa", "Allow view the sales report per box"),
	(24, 7, "RelatorioSessao", "Allow view the total sales of each session"),
	(25, 7, "RelatorioConsumo", "Allow printing of the table of the consumer report"),
	(26, 7, "RelatorioCozinha", "Allow reprinting of requests sent to the kitchen"),
	(27, 7, "RankDeVendas", "Allow view the ranking of employees in sales"),
	(28, 6, "CadastroProdutos", "Allow register or change a product"),
	(29, 6, "CadastroFornecedores", "Allow register or change a supplier"),
	(30, 6, "CadastroMesas", "Allow register or change a table"),
	(31, 6, "CadastroFuncionarios", "Allow subscribe or change an employee"),
	(32, 6, "CadastroFormasPagto", "Allow register or change a payment"),
	(33, 6, "CadastroPromocoes", "Allow register or change a promotion"),
	(34, 6, "CadastroCartoes", "Allow register or change a card"),
	(35, 6, "CadastroBancos", "Allow register or change a bank"),
	(36, 6, "CadastroCaixas", "Allow register or change a box"),
	(37, 6, "CadastroTiposDeContas", "Allow subscribe or change an account type"),
	(38, 6, "CadastroImpressoras", "Allow register or change a printer"),
	(39, 6, "CadastroComputadores", "Allow register or change a computer"),
	(40, 1, "ComputadorCaixa", "Allow access computers reserved for the box"),
	(41, 6, "CadastroClientes", "Allow register or change a customer"),
	(42, 1, "EntregaPedidos", "Allow access the product orders that are for delivery"),
	(43, 1, "AlterarAtendente", "Allow change the attendant at the time of sale"),
	(44, 2, "PedidoComanda", "Allow place orders for consumer cards"),
	(45, 6, "CadastroBairros", "Allow register or change information of a neighborhood"),
	(46, 6, "CadastroContas", "Allow register or change accounts payable or receivable"),
	(47, 7, "RelatorioContas", "Allow view account reports"),
	(48, 7, "RelatorioProdutos", "Allow view sales reports of products"),
	(49, 7, "RelatorioCompras", "Allow view Shopping reporting products"),
	(50, 6, "CadastroComandas", "Allow register or change a number of commands"),
	(51, 6, "CadastroServicos", "Allow register or change a fee or event"),
	(52, 2, "RealizarDescontos", "Allow hold discount sales"),
	(53, 3, "Comandas", "Allow access for sale for all you command"),
	(54, 4, "ExcluirPedidoFinalizado", "Allow delete an application that has already been finalized"),
	(55, 7, "RelatorioFuncionarios", "Allow viewing staff report"),
	(56, 7, "RelatorioClientes", "Allow customers to view report"),
	(57, 4, "RevogarComissao", "Allow removing the commission of an application"),
	(58, 1, "SelecionarEntregador", "Allow select another delivery in the delivery of orders for delivery"),
	(59, 3, "TransferirProdutos", "Allow transfer products from one table to another"),
	(60, 7, "RelatorioPedidos", "Allow view orders report"),
	(61, 8, "AlterarConfiguracoes", "Allow change the company information and system settings"),
	(62, 6, "ListaCompras", "Allow registering shopping list of products"),
	(63, 7, "RelatorioMensal", "Allow viewing and issue monthly sales reports"),
	(65, 6, "CadastroCidades", "Allow register or change the states of the cities"),
	(66, 5, "RetirarDoEstoque", "Allow take stock of products"),
	(67, 7, "RelatorioBairros", "Allow viewing neighborhoods reports"),
	(68, 1, "AlterarHorario", "Allow change the opening hours of the establishment"),
	(69, 6, "CadastrarCreditos", "Allow registering and change customer credit"),
	(70, 1, "AlterarStatus", "Allow changing the preparation conditions of the products"),
	(71, 7, "RelatorioEntrega", "Allow view delivery report for delivery"),
	(72, 7, "RelatorioFornecedores", "Allow viewing providers report"),
	(73, 3, "MudarDeComanda", "Allow change the order of a command to command"),
	(74, 7, "RelatorioAuditoria", "Allow view the audit report"),
	(75, 7, "RelatorioConsumidor", "Allow viewing the customer by sales report"),
	(76, 7, "RelatorioCreditos", "Allow customers view the credit report"),
	(77, 6, "CadastroCarteiras", "Allow registering wallets and bank accounts"),
	(78, 7, "RelatorioFluxo", "Allow view the cash flow report"),
	(79, 4, "TransferirValores", "Allow to transfer money from one box to another"),
	(80, 6, "CadastroPatrimonio", "Allow registering and updating the amount of assets of a company"),
	(81, 7, "RelatorioPatrimonio", "Allow view the list of assets of a company"),
	(82, 7, "RelatorioCarteiras", "Allow view the portfolio report"),
	(83, 7, "RelatorioCheques", "Allow view the check report"),
	(84, 2, "PagamentoConta", "Afford to pay an application in the form of payment account"),
	(85, 6, "CadastroPaises", "Allow register or change countries"),
	(86, 6, "CadastroEstados", "Allow register or change the status of a country"),
	(87, 6, "CadastroMoedas", "Allow register or change the types of coins"),
	(88, 8, "AlterarPaginas", "Allow change the pages of the company website"),
	(89, 1, "AlterarEntregador", "Allow change the delivery after sending the order"),
	(90, 7, "RelatorioBalanco", "Allow view the account balance report"),
	(91, 1, "TransformarEntrega", "Allow make a delivery request to travel and vice versa"),
	(92, 4, "ConferirCaixa", "Allow change conference values ​​of a box"),
	(93, 2, "ContaViagem", "Allow print requests account for travel"),
	(94, 2, "EntregaAdicionar", "Allow add products delivery screen"),
	(95, 1, "EntregarPedidos", "Allow delivery an order"),
	(96, 5, "InformarDesperdicio", "Allow reporting a waste when canceling a product");

INSERT INTO `Acessos` (`FuncaoID`, `PermissaoID`) VALUES
	(1, 1),
	(1, 3),
	(1, 4),
	(1, 5),
	(1, 6),
	(1, 7),
	(1, 8),
	(1, 9),
	(1, 10),
	(1, 11),
	(1, 12),
	(1, 13),
	(1, 14),
	(1, 15),
	(1, 16),
	(1, 17),
	(1, 18),
	(1, 19),
	(1, 20),
	(1, 21),
	(1, 22),
	(1, 23),
	(1, 24),
	(1, 25),
	(1, 26),
	(1, 27),
	(1, 28),
	(1, 29),
	(1, 30),
	(1, 31),
	(1, 32),
	(1, 33),
	(1, 34),
	(1, 35),
	(1, 36),
	(1, 37),
	(1, 38),
	(1, 39),
	(1, 40),
	(1, 41),
	(1, 42),
	(1, 43),
	(1, 44),
	(1, 45),
	(1, 46),
	(1, 47),
	(1, 48),
	(1, 49),
	(1, 50),
	(1, 51),
	(1, 52),
	(1, 53),
	(1, 54),
	(1, 55),
	(1, 56),
	(1, 57),
	(1, 58),
	(1, 59),
	(1, 60),
	(1, 61),
	(1, 62),
	(1, 63),
	(1, 65),
	(1, 66),
	(1, 67),
	(1, 68),
	(1, 69),
	(1, 70),
	(1, 71),
	(1, 72),
	(1, 73),
	(1, 74),
	(1, 75),
	(1, 76),
	(1, 77),
	(1, 78),
	(1, 79),
	(1, 80),
	(1, 81),
	(1, 82),
	(1, 83),
	(1, 84),
	(1, 85),
	(1, 86),
	(1, 87),
	(1, 88),
	(1, 89),
	(1, 90),
	(1, 91),
	(1, 92),
	(1, 93),
	(1, 94),
	(1, 95),
	(1, 96),
	(2, 1),
	(2, 4),
	(2, 6),
	(2, 8),
	(2, 16),
	(2, 21),
	(2, 22),
	(2, 25),
	(2, 44),
	(2, 53),
	(2, 60),
	(2, 73),
	(2, 93),
	(2, 94),
	(3, 1),
	(3, 4),
	(3, 5),
	(3, 6),
	(3, 8),
	(3, 9),
	(3, 11),
	(3, 12),
	(3, 13),
	(3, 14),
	(3, 16),
	(3, 21),
	(3, 22),
	(3, 25),
	(3, 26),
	(3, 41),
	(3, 42),
	(3, 43),
	(3, 44),
	(3, 46),
	(3, 47),
	(3, 48),
	(3, 49),
	(3, 51),
	(3, 53),
	(3, 58),
	(3, 59),
	(3, 60),
	(3, 70),
	(3, 73),
	(3, 76),
	(3, 79),
	(3, 84),
	(3, 89),
	(3, 91),
	(3, 93),
	(3, 94),
	(3, 96),
	(4, 1),
	(4, 70),
	(6, 1),
	(6, 42),
	(6, 45),
	(6, 65),
	(6, 71),
	(6, 95),
	(7, 1),
	(7, 17),
	(7, 28),
	(7, 29),
	(7, 66),
	(7, 72),
	(7, 80),
	(7, 81),
	(7, 96);

INSERT INTO `Setores` (`ID`, `Nome`, `Descricao`) VALUES
	(1, "Sales", "Sales sector"),
	(2, "Kitchen", "Kitchen sector"),
	(3, "Barbecue", "Barbecue sector"),
	(4, "Drinks", "Drinks sector");

INSERT INTO `Mesas` (`ID`, `Numero`, `Nome`, `Ativa`) VALUES
	(1, 1, "Table 1", 'Y'),
	(2, 2, "Table 2", 'Y'),
	(3, 3, "Table 3", 'Y'),
	(4, 4, "Table 4", 'Y'),
	(5, 5, "Table 5", 'Y'),
	(6, 6, "Table 6", 'Y'),
	(7, 7, "Table 7", 'Y'),
	(8, 8, "Table 8", 'Y'),
	(9, 9, "Table 9", 'Y'),
	(10, 10, "Table 10", 'Y');

INSERT INTO `Comandas` (`ID`, `Numero`, `Nome`, `Ativa`) VALUES
	(1, 1, "Card 1", 'Y'),
	(2, 2, "Card 2", 'Y'),
	(3, 3, "Card 3", 'Y'),
	(4, 4, "Card 4", 'Y'),
	(5, 5, "Card 5", 'Y'),
	(6, 6, "Card 6", 'Y'),
	(7, 7, "Card 7", 'Y'),
	(8, 8, "Card 8", 'Y'),
	(9, 9, "Card 9", 'Y'),
	(10, 10, "Card 10", 'Y');

INSERT INTO `Clientes` (`ID`, `Tipo`, `Login`, `Senha`, `Nome`, `Sobrenome`, `Genero`, `DataAtualizacao`, `DataCadastro`) VALUES
	(1, 'Fisica', "Admin", "e14268a48adfacfdaed1d420573f69df7ce4b829", "System", "administrator", 'Masculino', NOW(), NOW());

INSERT INTO `Prestadores` (`ID`, `Codigo`, `FuncaoID`, `ClienteID`, `Ativo`, `DataCadastro`) VALUES
	(1, 1, 1, 1, 'Y', NOW());

INSERT INTO `Carteiras` (`ID`, `Tipo`, `Descricao`, `Ativa`) VALUES
	(1, 'Local', "Company local account", 'Y'),
	(1, 'Local', "Cash drawer 1", 'Y');

INSERT INTO `Caixas` (`ID`, `CarteiraID`, `Descricao`, `Ativo`) VALUES
	(1, 2, "Cash register 1", 'Y');

INSERT INTO `Formas_Pagto` (`ID`, `Descricao`, `Tipo`, `CarteiraID`, `MinParcelas`, `MaxParcelas`, `ParcelasSemJuros`, `Juros`, `Ativa`) VALUES
	(1, "Money", 'Dinheiro', 1, NULL, NULL, NULL, NULL, 'Y'),
	(2, "Credit", 'Credito', 1, 1, 1, 1, 2.5, 'Y'),
	(3, "Debit", 'Debito', 1, 1, 1, 1, 2.5, 'Y'),
	(4, "Vale", 'Vale', 1, NULL, NULL, NULL, NULL, 'N'),
	(5, "Cheque", 'Cheque', 1, NULL, NULL, NULL, NULL, 'N'),
	(6, "Account", 'Crediario', 1, NULL, NULL, NULL, NULL, 'N'),
	(7, "Balance", 'Saldo', 1, NULL, NULL, NULL, NULL, 'N');

INSERT INTO `Cartoes` (`ID`, `FormaPagtoID`, `Bandeira`, `ImagemURL`, `Ativo`) VALUES
	(1, 2, "Visa", 'visa.png', 'Y'),
	(2, 2, "MasterCard", 'mastercard.png', 'Y'),
	(3, 2, "Hipercard", 'hipercard.png', 'Y'),
	(4, 2, "American Express", 'american_express.png', 'N'),
	(5, 2, "Diners Club", 'diners_club.png', 'N'),
	(6, 3, "Maestro", 'maestro.png', 'Y'),
	(7, 3, "Visa Electron", 'visa_electron.png', 'Y');

INSERT INTO `Categorias` (`ID`, `Descricao`, `Servico`, `DataAtualizacao`) VALUES
	(1, "Pizzas and pasta", 'Y', NOW()),
	(2, "Meals", 'Y', NOW()),
	(3, "Beers", 'N', NOW()),
	(4, "Soft drinks", 'N', NOW()),
	(5, "Juices", 'Y', NOW()),
	(6, "Energy drinks", 'N', NOW()),
	(7, "Cigarettes", 'N', NOW()),
	(8, "Distilled beverage", 'N', NOW()),
	(9, "Waters", 'N', NOW()),
	(10, "Snacks", 'Y', NOW()),
	(11, "Portions", 'Y', NOW()),
	(12, "Tropical drinks", 'N', NOW());

INSERT INTO `Unidades` (`Nome`, `Descricao`, `Sigla`) VALUES
	("Unity", "Unit", "UN"),
	("Litro", "Liquid unit", "L"),
	("Grama", "Weight unit", "g"),
	("Caloria", "Energy measurement unit", "cal"),
	("Joule", "Energy measurement unit", "J");

INSERT INTO `Classificacoes` (`ID`, `Descricao`) VALUES
	(1, "Cash register movements"),
	(2, "Bill payment");

INSERT INTO `Servicos` (`ID`, `Nome`, `Descricao`, `Tipo`, `Obrigatorio`, `Valor`, `Individual`, `Ativo`) VALUES
	(1, "Discount", "It allows to realize discounts in order", 'Taxa', 'N', 0, 'N', 'Y'),
	(2, "Delivery", "It allows you to charge rate for delivery", 'Taxa', 'N', 0, 'N', 'Y');

INSERT INTO `Bancos` (`Numero`, `RazaoSocial`, `AgenciaMascara`, `ContaMascara`) VALUES
	("1", "JPMorgan Chase & Co.", NULL, NULL),
	("2", "Bank of America Corp.", NULL, NULL),
	("3", "Citigroup Inc.", NULL, NULL),
	("4", "Wells Fargo & Co.", NULL, NULL),
	("5", "U.S. Bancorp", NULL, NULL),
	("6", "Bank of New York Mellon Corp.", NULL, NULL),
	("7", "PNC Financial Services Group Inc.", NULL, NULL),
	("8", "Capital One Financial Corp.", NULL, NULL),
	("9", "HSBC North American Holdings Inc.", NULL, NULL),
	("10", "TD Bank U.S. Holding Co.", NULL, NULL);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
