<?php

declare(strict_types=1);

return [
    // The prefix for routes
    'prefix' => 'graphql',

    // The routes to make GraphQL request. Either a string that will apply
    // to both query and mutation or an array containing the key 'query' and/or
    // 'mutation' with the according Route
    //
    // Example:
    //
    // Same route for both query and mutation
    //
    // 'routes' => 'path/to/query/{graphql_schema?}',
    //
    // or define each route
    //
    // 'routes' => [
    //     'query' => 'query/{graphql_schema?}',
    //     'mutation' => 'mutation/{graphql_schema?}',
    // ]
    //
    'routes' => '{graphql_schema?}',

    // The controller to use in GraphQL request. Either a string that will apply
    // to both query and mutation or an array containing the key 'query' and/or
    // 'mutation' with the according Controller and method
    //
    // Example:
    //
    // 'controllers' => [
    //     'query' => '\Rebing\GraphQL\GraphQLController@query',
    //     'mutation' => '\Rebing\GraphQL\GraphQLController@mutation'
    // ]
    //
    'controllers' => \Rebing\GraphQL\GraphQLController::class.'@query',

    // Any middleware for the graphql route group
    'middleware' => [],

    // Additional route group attributes
    //
    // Example:
    //
    // 'route_group_attributes' => ['guard' => 'api']
    //
    'route_group_attributes' => [],

    // The name of the default schema used when no argument is provided
    // to GraphQL::schema() or when the route is used without the graphql_schema
    // parameter.
    'default_schema' => 'default',

    // The schemas for query and/or mutation. It expects an array of schemas to provide
    // both the 'query' fields and the 'mutation' fields.
    //
    // You can also provide a middleware that will only apply to the given schema
    //
    // Example:
    //
    //  'schema' => 'default',
    //
    //  'schemas' => [
    //      'default' => [
    //          'query' => [
    //              'users' => 'App\GraphQL\Query\UsersQuery'
    //          ],
    //          'mutation' => [
    //
    //          ]
    //      ],
    //      'user' => [
    //          'query' => [
    //              'profile' => 'App\GraphQL\Query\ProfileQuery'
    //          ],
    //          'mutation' => [
    //
    //          ],
    //          'middleware' => ['auth'],
    //      ],
    //      'user/me' => [
    //          'query' => [
    //              'profile' => 'App\GraphQL\Query\MyProfileQuery'
    //          ],
    //          'mutation' => [
    //
    //          ],
    //          'middleware' => ['auth'],
    //      ],
    //  ]
    //
    'schemas' => [
        'default' => [
            'query' => [
                'setores' => 'App\GraphQL\Queries\SetorQuery',
                'mesas' => 'App\GraphQL\Queries\MesaQuery',
                'sessoes' => 'App\GraphQL\Queries\SessaoQuery',
                'bancos' => 'App\GraphQL\Queries\BancoQuery',
                'carteiras' => 'App\GraphQL\Queries\CarteiraQuery',
                'caixas' => 'App\GraphQL\Queries\CaixaQuery',
                'formas' => 'App\GraphQL\Queries\FormaQuery',
                'cartoes' => 'App\GraphQL\Queries\CartaoQuery',
                'funcoes' => 'App\GraphQL\Queries\FuncaoQuery',
                'clientes' => 'App\GraphQL\Queries\ClienteQuery',
                'prestadores' => 'App\GraphQL\Queries\PrestadorQuery',
                'moedas' => 'App\GraphQL\Queries\MoedaQuery',
                'paises' => 'App\GraphQL\Queries\PaisQuery',
                'estados' => 'App\GraphQL\Queries\EstadoQuery',
                'cidades' => 'App\GraphQL\Queries\CidadeQuery',
                'bairros' => 'App\GraphQL\Queries\BairroQuery',
                'zonas' => 'App\GraphQL\Queries\ZonaQuery',
                'localizacoes' => 'App\GraphQL\Queries\LocalizacaoQuery',
                'comandas' => 'App\GraphQL\Queries\ComandaQuery',
                'viagens' => 'App\GraphQL\Queries\ViagemQuery',
                'integracoes' => 'App\GraphQL\Queries\IntegracaoQuery',
                'associacoes' => 'App\GraphQL\Queries\AssociacaoQuery',
                'pedidos' => 'App\GraphQL\Queries\PedidoQuery',
                'categorias' => 'App\GraphQL\Queries\CategoriaQuery',
                'unidades' => 'App\GraphQL\Queries\UnidadeQuery',
                'origens' => 'App\GraphQL\Queries\OrigemQuery',
                'operacoes' => 'App\GraphQL\Queries\OperacaoQuery',
                'impostos' => 'App\GraphQL\Queries\ImpostoQuery',
                'tributacoes' => 'App\GraphQL\Queries\TributacaoQuery',
                'produtos' => 'App\GraphQL\Queries\ProdutoQuery',
                'servicos' => 'App\GraphQL\Queries\ServicoQuery',
                'classificacoes' => 'App\GraphQL\Queries\ClassificacaoQuery',
                'contas' => 'App\GraphQL\Queries\ContaQuery',
                'movimentacoes' => 'App\GraphQL\Queries\MovimentacaoQuery',
                'creditos' => 'App\GraphQL\Queries\CreditoQuery',
                'cheques' => 'App\GraphQL\Queries\ChequeQuery',
                'pagamentos' => 'App\GraphQL\Queries\PagamentoQuery',
                'itens' => 'App\GraphQL\Queries\ItemQuery',
                'modulos' => 'App\GraphQL\Queries\ModuloQuery',
                'funcionalidades' => 'App\GraphQL\Queries\FuncionalidadeQuery',
                'permissoes' => 'App\GraphQL\Queries\PermissaoQuery',
                'auditorias' => 'App\GraphQL\Queries\AuditoriaQuery',
                'composicoes' => 'App\GraphQL\Queries\ComposicaoQuery',
                'fornecedores' => 'App\GraphQL\Queries\FornecedorQuery',
                'listas' => 'App\GraphQL\Queries\ListaQuery',
                'compras' => 'App\GraphQL\Queries\CompraQuery',
                'requisitos' => 'App\GraphQL\Queries\RequisitoQuery',
                'estoques' => 'App\GraphQL\Queries\EstoqueQuery',
                'grupos' => 'App\GraphQL\Queries\GrupoQuery',
                'propriedades' => 'App\GraphQL\Queries\PropriedadeQuery',
                'pacotes' => 'App\GraphQL\Queries\PacoteQuery',
                'dispositivos' => 'App\GraphQL\Queries\DispositivoQuery',
                'impressoras' => 'App\GraphQL\Queries\ImpressoraQuery',
                'promocoes' => 'App\GraphQL\Queries\PromocaoQuery',
                'acessos' => 'App\GraphQL\Queries\AcessoQuery',
                'catalogos' => 'App\GraphQL\Queries\CatalogoQuery',
                'sistemas' => 'App\GraphQL\Queries\SistemaQuery',
                'resumos' => 'App\GraphQL\Queries\ResumoQuery',
                'formacoes' => 'App\GraphQL\Queries\FormacaoQuery',
                'enderecos' => 'App\GraphQL\Queries\EnderecoQuery',
                'horarios' => 'App\GraphQL\Queries\HorarioQuery',
                'patrimonios' => 'App\GraphQL\Queries\PatrimonioQuery',
                'juncoes' => 'App\GraphQL\Queries\JuncaoQuery',
                'regimes' => 'App\GraphQL\Queries\RegimeQuery',
                'emitentes' => 'App\GraphQL\Queries\EmitenteQuery',
                'notas' => 'App\GraphQL\Queries\NotaQuery',
                'eventos' => 'App\GraphQL\Queries\EventoQuery',
                'empresas' => 'App\GraphQL\Queries\EmpresaQuery',
                'pontuacoes' => 'App\GraphQL\Queries\PontuacaoQuery',
                'telefones' => 'App\GraphQL\Queries\TelefoneQuery',
                'observacoes' => 'App\GraphQL\Queries\ObservacaoQuery',
                'cupons' => 'App\GraphQL\Queries\CupomQuery',
                'metricas' => 'App\GraphQL\Queries\MetricaQuery',
                'avaliacoes' => 'App\GraphQL\Queries\AvaliacaoQuery',
                'cozinhas' => 'App\GraphQL\Queries\CozinhaQuery',
                'cardapios' => 'App\GraphQL\Queries\CardapioQuery',
                'contagens' => 'App\GraphQL\Queries\ContagemQuery',
            ],
            'mutation' => [
                'CreateSetor' => 'App\GraphQL\Mutations\CreateSetorMutation',
                'UpdateSetor' => 'App\GraphQL\Mutations\UpdateSetorMutation',
                'DeleteSetor' => 'App\GraphQL\Mutations\DeleteSetorMutation',
                'CreateMesa' => 'App\GraphQL\Mutations\CreateMesaMutation',
                'UpdateMesa' => 'App\GraphQL\Mutations\UpdateMesaMutation',
                'DeleteMesa' => 'App\GraphQL\Mutations\DeleteMesaMutation',
                'CreateSessao' => 'App\GraphQL\Mutations\CreateSessaoMutation',
                'UpdateSessao' => 'App\GraphQL\Mutations\UpdateSessaoMutation',
                'DeleteSessao' => 'App\GraphQL\Mutations\DeleteSessaoMutation',
                'CreateBanco' => 'App\GraphQL\Mutations\CreateBancoMutation',
                'UpdateBanco' => 'App\GraphQL\Mutations\UpdateBancoMutation',
                'DeleteBanco' => 'App\GraphQL\Mutations\DeleteBancoMutation',
                'CreateCarteira' => 'App\GraphQL\Mutations\CreateCarteiraMutation',
                'UpdateCarteira' => 'App\GraphQL\Mutations\UpdateCarteiraMutation',
                'DeleteCarteira' => 'App\GraphQL\Mutations\DeleteCarteiraMutation',
                'CreateCaixa' => 'App\GraphQL\Mutations\CreateCaixaMutation',
                'UpdateCaixa' => 'App\GraphQL\Mutations\UpdateCaixaMutation',
                'DeleteCaixa' => 'App\GraphQL\Mutations\DeleteCaixaMutation',
                'CreateForma' => 'App\GraphQL\Mutations\CreateFormaMutation',
                'UpdateForma' => 'App\GraphQL\Mutations\UpdateFormaMutation',
                'DeleteForma' => 'App\GraphQL\Mutations\DeleteFormaMutation',
                'CreateCartao' => 'App\GraphQL\Mutations\CreateCartaoMutation',
                'UpdateCartao' => 'App\GraphQL\Mutations\UpdateCartaoMutation',
                'DeleteCartao' => 'App\GraphQL\Mutations\DeleteCartaoMutation',
                'CreateFuncao' => 'App\GraphQL\Mutations\CreateFuncaoMutation',
                'UpdateFuncao' => 'App\GraphQL\Mutations\UpdateFuncaoMutation',
                'DeleteFuncao' => 'App\GraphQL\Mutations\DeleteFuncaoMutation',
                'CreateCliente' => 'App\GraphQL\Mutations\CreateClienteMutation',
                'UpdateCliente' => 'App\GraphQL\Mutations\UpdateClienteMutation',
                'DeleteCliente' => 'App\GraphQL\Mutations\DeleteClienteMutation',
                'CreatePrestador' => 'App\GraphQL\Mutations\CreatePrestadorMutation',
                'UpdatePrestador' => 'App\GraphQL\Mutations\UpdatePrestadorMutation',
                'DeletePrestador' => 'App\GraphQL\Mutations\DeletePrestadorMutation',
                'CreateMoeda' => 'App\GraphQL\Mutations\CreateMoedaMutation',
                'UpdateMoeda' => 'App\GraphQL\Mutations\UpdateMoedaMutation',
                'DeleteMoeda' => 'App\GraphQL\Mutations\DeleteMoedaMutation',
                'CreatePais' => 'App\GraphQL\Mutations\CreatePaisMutation',
                'UpdatePais' => 'App\GraphQL\Mutations\UpdatePaisMutation',
                'DeletePais' => 'App\GraphQL\Mutations\DeletePaisMutation',
                'CreateEstado' => 'App\GraphQL\Mutations\CreateEstadoMutation',
                'UpdateEstado' => 'App\GraphQL\Mutations\UpdateEstadoMutation',
                'DeleteEstado' => 'App\GraphQL\Mutations\DeleteEstadoMutation',
                'CreateCidade' => 'App\GraphQL\Mutations\CreateCidadeMutation',
                'UpdateCidade' => 'App\GraphQL\Mutations\UpdateCidadeMutation',
                'DeleteCidade' => 'App\GraphQL\Mutations\DeleteCidadeMutation',
                'CreateBairro' => 'App\GraphQL\Mutations\CreateBairroMutation',
                'UpdateBairro' => 'App\GraphQL\Mutations\UpdateBairroMutation',
                'DeleteBairro' => 'App\GraphQL\Mutations\DeleteBairroMutation',
                'CreateZona' => 'App\GraphQL\Mutations\CreateZonaMutation',
                'UpdateZona' => 'App\GraphQL\Mutations\UpdateZonaMutation',
                'DeleteZona' => 'App\GraphQL\Mutations\DeleteZonaMutation',
                'CreateLocalizacao' => 'App\GraphQL\Mutations\CreateLocalizacaoMutation',
                'UpdateLocalizacao' => 'App\GraphQL\Mutations\UpdateLocalizacaoMutation',
                'DeleteLocalizacao' => 'App\GraphQL\Mutations\DeleteLocalizacaoMutation',
                'CreateComanda' => 'App\GraphQL\Mutations\CreateComandaMutation',
                'UpdateComanda' => 'App\GraphQL\Mutations\UpdateComandaMutation',
                'DeleteComanda' => 'App\GraphQL\Mutations\DeleteComandaMutation',
                'CreateViagem' => 'App\GraphQL\Mutations\CreateViagemMutation',
                'UpdateViagem' => 'App\GraphQL\Mutations\UpdateViagemMutation',
                'DeleteViagem' => 'App\GraphQL\Mutations\DeleteViagemMutation',
                'CreateIntegracao' => 'App\GraphQL\Mutations\CreateIntegracaoMutation',
                'UpdateIntegracao' => 'App\GraphQL\Mutations\UpdateIntegracaoMutation',
                'DeleteIntegracao' => 'App\GraphQL\Mutations\DeleteIntegracaoMutation',
                'CreateAssociacao' => 'App\GraphQL\Mutations\CreateAssociacaoMutation',
                'UpdateAssociacao' => 'App\GraphQL\Mutations\UpdateAssociacaoMutation',
                'DeleteAssociacao' => 'App\GraphQL\Mutations\DeleteAssociacaoMutation',
                'CreatePedido' => 'App\GraphQL\Mutations\CreatePedidoMutation',
                'UpdatePedido' => 'App\GraphQL\Mutations\UpdatePedidoMutation',
                'DeletePedido' => 'App\GraphQL\Mutations\DeletePedidoMutation',
                'CreateCategoria' => 'App\GraphQL\Mutations\CreateCategoriaMutation',
                'UpdateCategoria' => 'App\GraphQL\Mutations\UpdateCategoriaMutation',
                'DeleteCategoria' => 'App\GraphQL\Mutations\DeleteCategoriaMutation',
                'CreateUnidade' => 'App\GraphQL\Mutations\CreateUnidadeMutation',
                'UpdateUnidade' => 'App\GraphQL\Mutations\UpdateUnidadeMutation',
                'DeleteUnidade' => 'App\GraphQL\Mutations\DeleteUnidadeMutation',
                'CreateOrigem' => 'App\GraphQL\Mutations\CreateOrigemMutation',
                'UpdateOrigem' => 'App\GraphQL\Mutations\UpdateOrigemMutation',
                'DeleteOrigem' => 'App\GraphQL\Mutations\DeleteOrigemMutation',
                'CreateOperacao' => 'App\GraphQL\Mutations\CreateOperacaoMutation',
                'UpdateOperacao' => 'App\GraphQL\Mutations\UpdateOperacaoMutation',
                'DeleteOperacao' => 'App\GraphQL\Mutations\DeleteOperacaoMutation',
                'CreateImposto' => 'App\GraphQL\Mutations\CreateImpostoMutation',
                'UpdateImposto' => 'App\GraphQL\Mutations\UpdateImpostoMutation',
                'DeleteImposto' => 'App\GraphQL\Mutations\DeleteImpostoMutation',
                'CreateTributacao' => 'App\GraphQL\Mutations\CreateTributacaoMutation',
                'UpdateTributacao' => 'App\GraphQL\Mutations\UpdateTributacaoMutation',
                'DeleteTributacao' => 'App\GraphQL\Mutations\DeleteTributacaoMutation',
                'CreateProduto' => 'App\GraphQL\Mutations\CreateProdutoMutation',
                'UpdateProduto' => 'App\GraphQL\Mutations\UpdateProdutoMutation',
                'DeleteProduto' => 'App\GraphQL\Mutations\DeleteProdutoMutation',
                'CreateServico' => 'App\GraphQL\Mutations\CreateServicoMutation',
                'UpdateServico' => 'App\GraphQL\Mutations\UpdateServicoMutation',
                'DeleteServico' => 'App\GraphQL\Mutations\DeleteServicoMutation',
                'CreateClassificacao' => 'App\GraphQL\Mutations\CreateClassificacaoMutation',
                'UpdateClassificacao' => 'App\GraphQL\Mutations\UpdateClassificacaoMutation',
                'DeleteClassificacao' => 'App\GraphQL\Mutations\DeleteClassificacaoMutation',
                'CreateConta' => 'App\GraphQL\Mutations\CreateContaMutation',
                'UpdateConta' => 'App\GraphQL\Mutations\UpdateContaMutation',
                'DeleteConta' => 'App\GraphQL\Mutations\DeleteContaMutation',
                'CreateMovimentacao' => 'App\GraphQL\Mutations\CreateMovimentacaoMutation',
                'UpdateMovimentacao' => 'App\GraphQL\Mutations\UpdateMovimentacaoMutation',
                'DeleteMovimentacao' => 'App\GraphQL\Mutations\DeleteMovimentacaoMutation',
                'CreateCredito' => 'App\GraphQL\Mutations\CreateCreditoMutation',
                'UpdateCredito' => 'App\GraphQL\Mutations\UpdateCreditoMutation',
                'DeleteCredito' => 'App\GraphQL\Mutations\DeleteCreditoMutation',
                'CreateCheque' => 'App\GraphQL\Mutations\CreateChequeMutation',
                'UpdateCheque' => 'App\GraphQL\Mutations\UpdateChequeMutation',
                'DeleteCheque' => 'App\GraphQL\Mutations\DeleteChequeMutation',
                'CreatePagamento' => 'App\GraphQL\Mutations\CreatePagamentoMutation',
                'UpdatePagamento' => 'App\GraphQL\Mutations\UpdatePagamentoMutation',
                'DeletePagamento' => 'App\GraphQL\Mutations\DeletePagamentoMutation',
                'CreateItem' => 'App\GraphQL\Mutations\CreateItemMutation',
                'UpdateItem' => 'App\GraphQL\Mutations\UpdateItemMutation',
                'DeleteItem' => 'App\GraphQL\Mutations\DeleteItemMutation',
                'CreateModulo' => 'App\GraphQL\Mutations\CreateModuloMutation',
                'UpdateModulo' => 'App\GraphQL\Mutations\UpdateModuloMutation',
                'DeleteModulo' => 'App\GraphQL\Mutations\DeleteModuloMutation',
                'CreateFuncionalidade' => 'App\GraphQL\Mutations\CreateFuncionalidadeMutation',
                'UpdateFuncionalidade' => 'App\GraphQL\Mutations\UpdateFuncionalidadeMutation',
                'DeleteFuncionalidade' => 'App\GraphQL\Mutations\DeleteFuncionalidadeMutation',
                'CreatePermissao' => 'App\GraphQL\Mutations\CreatePermissaoMutation',
                'UpdatePermissao' => 'App\GraphQL\Mutations\UpdatePermissaoMutation',
                'DeletePermissao' => 'App\GraphQL\Mutations\DeletePermissaoMutation',
                'CreateAuditoria' => 'App\GraphQL\Mutations\CreateAuditoriaMutation',
                'UpdateAuditoria' => 'App\GraphQL\Mutations\UpdateAuditoriaMutation',
                'DeleteAuditoria' => 'App\GraphQL\Mutations\DeleteAuditoriaMutation',
                'CreateComposicao' => 'App\GraphQL\Mutations\CreateComposicaoMutation',
                'UpdateComposicao' => 'App\GraphQL\Mutations\UpdateComposicaoMutation',
                'DeleteComposicao' => 'App\GraphQL\Mutations\DeleteComposicaoMutation',
                'CreateFornecedor' => 'App\GraphQL\Mutations\CreateFornecedorMutation',
                'UpdateFornecedor' => 'App\GraphQL\Mutations\UpdateFornecedorMutation',
                'DeleteFornecedor' => 'App\GraphQL\Mutations\DeleteFornecedorMutation',
                'CreateLista' => 'App\GraphQL\Mutations\CreateListaMutation',
                'UpdateLista' => 'App\GraphQL\Mutations\UpdateListaMutation',
                'DeleteLista' => 'App\GraphQL\Mutations\DeleteListaMutation',
                'CreateCompra' => 'App\GraphQL\Mutations\CreateCompraMutation',
                'UpdateCompra' => 'App\GraphQL\Mutations\UpdateCompraMutation',
                'DeleteCompra' => 'App\GraphQL\Mutations\DeleteCompraMutation',
                'CreateRequisito' => 'App\GraphQL\Mutations\CreateRequisitoMutation',
                'UpdateRequisito' => 'App\GraphQL\Mutations\UpdateRequisitoMutation',
                'DeleteRequisito' => 'App\GraphQL\Mutations\DeleteRequisitoMutation',
                'CreateEstoque' => 'App\GraphQL\Mutations\CreateEstoqueMutation',
                'UpdateEstoque' => 'App\GraphQL\Mutations\UpdateEstoqueMutation',
                'DeleteEstoque' => 'App\GraphQL\Mutations\DeleteEstoqueMutation',
                'CreateGrupo' => 'App\GraphQL\Mutations\CreateGrupoMutation',
                'UpdateGrupo' => 'App\GraphQL\Mutations\UpdateGrupoMutation',
                'DeleteGrupo' => 'App\GraphQL\Mutations\DeleteGrupoMutation',
                'CreatePropriedade' => 'App\GraphQL\Mutations\CreatePropriedadeMutation',
                'UpdatePropriedade' => 'App\GraphQL\Mutations\UpdatePropriedadeMutation',
                'DeletePropriedade' => 'App\GraphQL\Mutations\DeletePropriedadeMutation',
                'CreatePacote' => 'App\GraphQL\Mutations\CreatePacoteMutation',
                'UpdatePacote' => 'App\GraphQL\Mutations\UpdatePacoteMutation',
                'DeletePacote' => 'App\GraphQL\Mutations\DeletePacoteMutation',
                'CreateDispositivo' => 'App\GraphQL\Mutations\CreateDispositivoMutation',
                'UpdateDispositivo' => 'App\GraphQL\Mutations\UpdateDispositivoMutation',
                'DeleteDispositivo' => 'App\GraphQL\Mutations\DeleteDispositivoMutation',
                'CreateImpressora' => 'App\GraphQL\Mutations\CreateImpressoraMutation',
                'UpdateImpressora' => 'App\GraphQL\Mutations\UpdateImpressoraMutation',
                'DeleteImpressora' => 'App\GraphQL\Mutations\DeleteImpressoraMutation',
                'CreatePromocao' => 'App\GraphQL\Mutations\CreatePromocaoMutation',
                'UpdatePromocao' => 'App\GraphQL\Mutations\UpdatePromocaoMutation',
                'DeletePromocao' => 'App\GraphQL\Mutations\DeletePromocaoMutation',
                'CreateAcesso' => 'App\GraphQL\Mutations\CreateAcessoMutation',
                'UpdateAcesso' => 'App\GraphQL\Mutations\UpdateAcessoMutation',
                'DeleteAcesso' => 'App\GraphQL\Mutations\DeleteAcessoMutation',
                'CreateCatalogo' => 'App\GraphQL\Mutations\CreateCatalogoMutation',
                'UpdateCatalogo' => 'App\GraphQL\Mutations\UpdateCatalogoMutation',
                'DeleteCatalogo' => 'App\GraphQL\Mutations\DeleteCatalogoMutation',
                'CreateSistema' => 'App\GraphQL\Mutations\CreateSistemaMutation',
                'UpdateSistema' => 'App\GraphQL\Mutations\UpdateSistemaMutation',
                'DeleteSistema' => 'App\GraphQL\Mutations\DeleteSistemaMutation',
                'CreateResumo' => 'App\GraphQL\Mutations\CreateResumoMutation',
                'UpdateResumo' => 'App\GraphQL\Mutations\UpdateResumoMutation',
                'DeleteResumo' => 'App\GraphQL\Mutations\DeleteResumoMutation',
                'CreateFormacao' => 'App\GraphQL\Mutations\CreateFormacaoMutation',
                'UpdateFormacao' => 'App\GraphQL\Mutations\UpdateFormacaoMutation',
                'DeleteFormacao' => 'App\GraphQL\Mutations\DeleteFormacaoMutation',
                'CreateEndereco' => 'App\GraphQL\Mutations\CreateEnderecoMutation',
                'UpdateEndereco' => 'App\GraphQL\Mutations\UpdateEnderecoMutation',
                'DeleteEndereco' => 'App\GraphQL\Mutations\DeleteEnderecoMutation',
                'CreateHorario' => 'App\GraphQL\Mutations\CreateHorarioMutation',
                'UpdateHorario' => 'App\GraphQL\Mutations\UpdateHorarioMutation',
                'DeleteHorario' => 'App\GraphQL\Mutations\DeleteHorarioMutation',
                'CreatePatrimonio' => 'App\GraphQL\Mutations\CreatePatrimonioMutation',
                'UpdatePatrimonio' => 'App\GraphQL\Mutations\UpdatePatrimonioMutation',
                'DeletePatrimonio' => 'App\GraphQL\Mutations\DeletePatrimonioMutation',
                'CreateJuncao' => 'App\GraphQL\Mutations\CreateJuncaoMutation',
                'UpdateJuncao' => 'App\GraphQL\Mutations\UpdateJuncaoMutation',
                'DeleteJuncao' => 'App\GraphQL\Mutations\DeleteJuncaoMutation',
                'CreateRegime' => 'App\GraphQL\Mutations\CreateRegimeMutation',
                'UpdateRegime' => 'App\GraphQL\Mutations\UpdateRegimeMutation',
                'DeleteRegime' => 'App\GraphQL\Mutations\DeleteRegimeMutation',
                'CreateEmitente' => 'App\GraphQL\Mutations\CreateEmitenteMutation',
                'UpdateEmitente' => 'App\GraphQL\Mutations\UpdateEmitenteMutation',
                'DeleteEmitente' => 'App\GraphQL\Mutations\DeleteEmitenteMutation',
                'CreateNota' => 'App\GraphQL\Mutations\CreateNotaMutation',
                'UpdateNota' => 'App\GraphQL\Mutations\UpdateNotaMutation',
                'DeleteNota' => 'App\GraphQL\Mutations\DeleteNotaMutation',
                'CreateEvento' => 'App\GraphQL\Mutations\CreateEventoMutation',
                'UpdateEvento' => 'App\GraphQL\Mutations\UpdateEventoMutation',
                'DeleteEvento' => 'App\GraphQL\Mutations\DeleteEventoMutation',
                'CreateEmpresa' => 'App\GraphQL\Mutations\CreateEmpresaMutation',
                'UpdateEmpresa' => 'App\GraphQL\Mutations\UpdateEmpresaMutation',
                'DeleteEmpresa' => 'App\GraphQL\Mutations\DeleteEmpresaMutation',
                'CreatePontuacao' => 'App\GraphQL\Mutations\CreatePontuacaoMutation',
                'UpdatePontuacao' => 'App\GraphQL\Mutations\UpdatePontuacaoMutation',
                'DeletePontuacao' => 'App\GraphQL\Mutations\DeletePontuacaoMutation',
                'CreateTelefone' => 'App\GraphQL\Mutations\CreateTelefoneMutation',
                'UpdateTelefone' => 'App\GraphQL\Mutations\UpdateTelefoneMutation',
                'DeleteTelefone' => 'App\GraphQL\Mutations\DeleteTelefoneMutation',
                'CreateObservacao' => 'App\GraphQL\Mutations\CreateObservacaoMutation',
                'UpdateObservacao' => 'App\GraphQL\Mutations\UpdateObservacaoMutation',
                'DeleteObservacao' => 'App\GraphQL\Mutations\DeleteObservacaoMutation',
                'CreateCupom' => 'App\GraphQL\Mutations\CreateCupomMutation',
                'UpdateCupom' => 'App\GraphQL\Mutations\UpdateCupomMutation',
                'DeleteCupom' => 'App\GraphQL\Mutations\DeleteCupomMutation',
                'CreateMetrica' => 'App\GraphQL\Mutations\CreateMetricaMutation',
                'UpdateMetrica' => 'App\GraphQL\Mutations\UpdateMetricaMutation',
                'DeleteMetrica' => 'App\GraphQL\Mutations\DeleteMetricaMutation',
                'CreateAvaliacao' => 'App\GraphQL\Mutations\CreateAvaliacaoMutation',
                'UpdateAvaliacao' => 'App\GraphQL\Mutations\UpdateAvaliacaoMutation',
                'DeleteAvaliacao' => 'App\GraphQL\Mutations\DeleteAvaliacaoMutation',
                'CreateCozinha' => 'App\GraphQL\Mutations\CreateCozinhaMutation',
                'UpdateCozinha' => 'App\GraphQL\Mutations\UpdateCozinhaMutation',
                'DeleteCozinha' => 'App\GraphQL\Mutations\DeleteCozinhaMutation',
                'CreateCardapio' => 'App\GraphQL\Mutations\CreateCardapioMutation',
                'UpdateCardapio' => 'App\GraphQL\Mutations\UpdateCardapioMutation',
                'DeleteCardapio' => 'App\GraphQL\Mutations\DeleteCardapioMutation',
                'CreateContagem' => 'App\GraphQL\Mutations\CreateContagemMutation',
                'UpdateContagem' => 'App\GraphQL\Mutations\UpdateContagemMutation',
                'DeleteContagem' => 'App\GraphQL\Mutations\DeleteContagemMutation',
            ],
            'middleware' => [],
            'method'     => ['get', 'post'],
        ],
    ],

    // The types available in the application. You can then access it from the
    // facade like this: GraphQL::type('user')
    //
    // Example:
    //
    // 'types' => [
    //     'user' => 'App\GraphQL\Type\UserType'
    // ]
    //
    'types' => [
        'Date' => 'App\GraphQL\Types\DateType',
        'DateTime' => 'App\GraphQL\Types\DateTimeType',

        'StringFilter' => 'App\GraphQL\Unions\StringUnion',
        'NumberFilter' => 'App\GraphQL\Unions\NumberUnion',
        'DateFilter' => 'App\GraphQL\Unions\DateUnion',

        'StringInput' => 'App\GraphQL\Inputs\StringInput',
        'NumberInput' => 'App\GraphQL\Inputs\NumberInput',
        'DateInput' => 'App\GraphQL\Inputs\DateInput',
        'DateRangeInput' => 'App\GraphQL\Inputs\DateRangeInput',

        'OrderByEnum' => 'App\GraphQL\Enums\OrderByEnum',

        'SetorFilter' => 'App\GraphQL\Filters\SetorFilter',
        'MesaFilter' => 'App\GraphQL\Filters\MesaFilter',
        'SessaoFilter' => 'App\GraphQL\Filters\SessaoFilter',
        'BancoFilter' => 'App\GraphQL\Filters\BancoFilter',
        'CarteiraFilter' => 'App\GraphQL\Filters\CarteiraFilter',
        'CaixaFilter' => 'App\GraphQL\Filters\CaixaFilter',
        'FormaFilter' => 'App\GraphQL\Filters\FormaFilter',
        'CartaoFilter' => 'App\GraphQL\Filters\CartaoFilter',
        'FuncaoFilter' => 'App\GraphQL\Filters\FuncaoFilter',
        'ClienteFilter' => 'App\GraphQL\Filters\ClienteFilter',
        'PrestadorFilter' => 'App\GraphQL\Filters\PrestadorFilter',
        'MoedaFilter' => 'App\GraphQL\Filters\MoedaFilter',
        'PaisFilter' => 'App\GraphQL\Filters\PaisFilter',
        'EstadoFilter' => 'App\GraphQL\Filters\EstadoFilter',
        'CidadeFilter' => 'App\GraphQL\Filters\CidadeFilter',
        'BairroFilter' => 'App\GraphQL\Filters\BairroFilter',
        'ZonaFilter' => 'App\GraphQL\Filters\ZonaFilter',
        'LocalizacaoFilter' => 'App\GraphQL\Filters\LocalizacaoFilter',
        'ComandaFilter' => 'App\GraphQL\Filters\ComandaFilter',
        'ViagemFilter' => 'App\GraphQL\Filters\ViagemFilter',
        'IntegracaoFilter' => 'App\GraphQL\Filters\IntegracaoFilter',
        'AssociacaoFilter' => 'App\GraphQL\Filters\AssociacaoFilter',
        'PedidoFilter' => 'App\GraphQL\Filters\PedidoFilter',
        'CategoriaFilter' => 'App\GraphQL\Filters\CategoriaFilter',
        'UnidadeFilter' => 'App\GraphQL\Filters\UnidadeFilter',
        'OrigemFilter' => 'App\GraphQL\Filters\OrigemFilter',
        'OperacaoFilter' => 'App\GraphQL\Filters\OperacaoFilter',
        'ImpostoFilter' => 'App\GraphQL\Filters\ImpostoFilter',
        'TributacaoFilter' => 'App\GraphQL\Filters\TributacaoFilter',
        'ProdutoFilter' => 'App\GraphQL\Filters\ProdutoFilter',
        'ServicoFilter' => 'App\GraphQL\Filters\ServicoFilter',
        'ClassificacaoFilter' => 'App\GraphQL\Filters\ClassificacaoFilter',
        'ContaFilter' => 'App\GraphQL\Filters\ContaFilter',
        'MovimentacaoFilter' => 'App\GraphQL\Filters\MovimentacaoFilter',
        'CreditoFilter' => 'App\GraphQL\Filters\CreditoFilter',
        'ChequeFilter' => 'App\GraphQL\Filters\ChequeFilter',
        'PagamentoFilter' => 'App\GraphQL\Filters\PagamentoFilter',
        'ItemFilter' => 'App\GraphQL\Filters\ItemFilter',
        'ModuloFilter' => 'App\GraphQL\Filters\ModuloFilter',
        'FuncionalidadeFilter' => 'App\GraphQL\Filters\FuncionalidadeFilter',
        'PermissaoFilter' => 'App\GraphQL\Filters\PermissaoFilter',
        'AuditoriaFilter' => 'App\GraphQL\Filters\AuditoriaFilter',
        'ComposicaoFilter' => 'App\GraphQL\Filters\ComposicaoFilter',
        'FornecedorFilter' => 'App\GraphQL\Filters\FornecedorFilter',
        'ListaFilter' => 'App\GraphQL\Filters\ListaFilter',
        'CompraFilter' => 'App\GraphQL\Filters\CompraFilter',
        'RequisitoFilter' => 'App\GraphQL\Filters\RequisitoFilter',
        'EstoqueFilter' => 'App\GraphQL\Filters\EstoqueFilter',
        'GrupoFilter' => 'App\GraphQL\Filters\GrupoFilter',
        'PropriedadeFilter' => 'App\GraphQL\Filters\PropriedadeFilter',
        'PacoteFilter' => 'App\GraphQL\Filters\PacoteFilter',
        'DispositivoFilter' => 'App\GraphQL\Filters\DispositivoFilter',
        'ImpressoraFilter' => 'App\GraphQL\Filters\ImpressoraFilter',
        'PromocaoFilter' => 'App\GraphQL\Filters\PromocaoFilter',
        'AcessoFilter' => 'App\GraphQL\Filters\AcessoFilter',
        'CatalogoFilter' => 'App\GraphQL\Filters\CatalogoFilter',
        'SistemaFilter' => 'App\GraphQL\Filters\SistemaFilter',
        'ResumoFilter' => 'App\GraphQL\Filters\ResumoFilter',
        'FormacaoFilter' => 'App\GraphQL\Filters\FormacaoFilter',
        'EnderecoFilter' => 'App\GraphQL\Filters\EnderecoFilter',
        'HorarioFilter' => 'App\GraphQL\Filters\HorarioFilter',
        'PatrimonioFilter' => 'App\GraphQL\Filters\PatrimonioFilter',
        'JuncaoFilter' => 'App\GraphQL\Filters\JuncaoFilter',
        'RegimeFilter' => 'App\GraphQL\Filters\RegimeFilter',
        'EmitenteFilter' => 'App\GraphQL\Filters\EmitenteFilter',
        'NotaFilter' => 'App\GraphQL\Filters\NotaFilter',
        'EventoFilter' => 'App\GraphQL\Filters\EventoFilter',
        'EmpresaFilter' => 'App\GraphQL\Filters\EmpresaFilter',
        'PontuacaoFilter' => 'App\GraphQL\Filters\PontuacaoFilter',
        'TelefoneFilter' => 'App\GraphQL\Filters\TelefoneFilter',
        'ObservacaoFilter' => 'App\GraphQL\Filters\ObservacaoFilter',
        'CupomFilter' => 'App\GraphQL\Filters\CupomFilter',
        'MetricaFilter' => 'App\GraphQL\Filters\MetricaFilter',
        'AvaliacaoFilter' => 'App\GraphQL\Filters\AvaliacaoFilter',
        'CozinhaFilter' => 'App\GraphQL\Filters\CozinhaFilter',
        'CardapioFilter' => 'App\GraphQL\Filters\CardapioFilter',
        'ContagemFilter' => 'App\GraphQL\Filters\ContagemFilter',

        'CarteiraTipoFilter' => 'App\GraphQL\Unions\CarteiraTipoUnion',
        'CarteiraAmbienteFilter' => 'App\GraphQL\Unions\CarteiraAmbienteUnion',
        'FormaTipoFilter' => 'App\GraphQL\Unions\FormaTipoUnion',
        'ClienteTipoFilter' => 'App\GraphQL\Unions\ClienteTipoUnion',
        'ClienteGeneroFilter' => 'App\GraphQL\Unions\ClienteGeneroUnion',
        'ClienteStatusFilter' => 'App\GraphQL\Unions\ClienteStatusUnion',
        'PrestadorVinculoFilter' => 'App\GraphQL\Unions\PrestadorVinculoUnion',
        'LocalizacaoTipoFilter' => 'App\GraphQL\Unions\LocalizacaoTipoUnion',
        'AssociacaoStatusFilter' => 'App\GraphQL\Unions\AssociacaoStatusUnion',
        'PedidoTipoFilter' => 'App\GraphQL\Unions\PedidoTipoUnion',
        'PedidoEstadoFilter' => 'App\GraphQL\Unions\PedidoEstadoUnion',
        'ImpostoGrupoFilter' => 'App\GraphQL\Unions\ImpostoGrupoUnion',
        'ProdutoTipoFilter' => 'App\GraphQL\Unions\ProdutoTipoUnion',
        'ServicoTipoFilter' => 'App\GraphQL\Unions\ServicoTipoUnion',
        'ContaTipoFilter' => 'App\GraphQL\Unions\ContaTipoUnion',
        'ContaFonteFilter' => 'App\GraphQL\Unions\ContaFonteUnion',
        'ContaModoFilter' => 'App\GraphQL\Unions\ContaModoUnion',
        'ContaFormulaFilter' => 'App\GraphQL\Unions\ContaFormulaUnion',
        'ContaEstadoFilter' => 'App\GraphQL\Unions\ContaEstadoUnion',
        'PagamentoEstadoFilter' => 'App\GraphQL\Unions\PagamentoEstadoUnion',
        'ItemEstadoFilter' => 'App\GraphQL\Unions\ItemEstadoUnion',
        'AuditoriaTipoFilter' => 'App\GraphQL\Unions\AuditoriaTipoUnion',
        'AuditoriaPrioridadeFilter' => 'App\GraphQL\Unions\AuditoriaPrioridadeUnion',
        'ComposicaoTipoFilter' => 'App\GraphQL\Unions\ComposicaoTipoUnion',
        'ListaEstadoFilter' => 'App\GraphQL\Unions\ListaEstadoUnion',
        'GrupoTipoFilter' => 'App\GraphQL\Unions\GrupoTipoUnion',
        'GrupoFuncaoFilter' => 'App\GraphQL\Unions\GrupoFuncaoUnion',
        'DispositivoTipoFilter' => 'App\GraphQL\Unions\DispositivoTipoUnion',
        'ImpressoraModoFilter' => 'App\GraphQL\Unions\ImpressoraModoUnion',
        'PromocaoLocalFilter' => 'App\GraphQL\Unions\PromocaoLocalUnion',
        'PromocaoFuncaoVendasFilter' => 'App\GraphQL\Unions\PromocaoFuncaoVendasUnion',
        'PromocaoFuncaoClienteFilter' => 'App\GraphQL\Unions\PromocaoFuncaoClienteUnion',
        'HorarioModoFilter' => 'App\GraphQL\Unions\HorarioModoUnion',
        'PatrimonioEstadoFilter' => 'App\GraphQL\Unions\PatrimonioEstadoUnion',
        'JuncaoEstadoFilter' => 'App\GraphQL\Unions\JuncaoEstadoUnion',
        'EmitenteAmbienteFilter' => 'App\GraphQL\Unions\EmitenteAmbienteUnion',
        'NotaTipoFilter' => 'App\GraphQL\Unions\NotaTipoUnion',
        'NotaAmbienteFilter' => 'App\GraphQL\Unions\NotaAmbienteUnion',
        'NotaAcaoFilter' => 'App\GraphQL\Unions\NotaAcaoUnion',
        'NotaEstadoFilter' => 'App\GraphQL\Unions\NotaEstadoUnion',
        'EventoEstadoFilter' => 'App\GraphQL\Unions\EventoEstadoUnion',
        'CupomTipoDescontoFilter' => 'App\GraphQL\Unions\CupomTipoDescontoUnion',
        'CupomFuncaoPedidosFilter' => 'App\GraphQL\Unions\CupomFuncaoPedidosUnion',
        'CupomFuncaoValorFilter' => 'App\GraphQL\Unions\CupomFuncaoValorUnion',
        'MetricaTipoFilter' => 'App\GraphQL\Unions\MetricaTipoUnion',
        'CardapioLocalFilter' => 'App\GraphQL\Unions\CardapioLocalUnion',

        'SetorOrder' => 'App\GraphQL\Ordering\SetorOrder',
        'MesaOrder' => 'App\GraphQL\Ordering\MesaOrder',
        'SessaoOrder' => 'App\GraphQL\Ordering\SessaoOrder',
        'BancoOrder' => 'App\GraphQL\Ordering\BancoOrder',
        'CarteiraOrder' => 'App\GraphQL\Ordering\CarteiraOrder',
        'CaixaOrder' => 'App\GraphQL\Ordering\CaixaOrder',
        'FormaOrder' => 'App\GraphQL\Ordering\FormaOrder',
        'CartaoOrder' => 'App\GraphQL\Ordering\CartaoOrder',
        'FuncaoOrder' => 'App\GraphQL\Ordering\FuncaoOrder',
        'ClienteOrder' => 'App\GraphQL\Ordering\ClienteOrder',
        'PrestadorOrder' => 'App\GraphQL\Ordering\PrestadorOrder',
        'MoedaOrder' => 'App\GraphQL\Ordering\MoedaOrder',
        'PaisOrder' => 'App\GraphQL\Ordering\PaisOrder',
        'EstadoOrder' => 'App\GraphQL\Ordering\EstadoOrder',
        'CidadeOrder' => 'App\GraphQL\Ordering\CidadeOrder',
        'BairroOrder' => 'App\GraphQL\Ordering\BairroOrder',
        'ZonaOrder' => 'App\GraphQL\Ordering\ZonaOrder',
        'LocalizacaoOrder' => 'App\GraphQL\Ordering\LocalizacaoOrder',
        'ComandaOrder' => 'App\GraphQL\Ordering\ComandaOrder',
        'ViagemOrder' => 'App\GraphQL\Ordering\ViagemOrder',
        'IntegracaoOrder' => 'App\GraphQL\Ordering\IntegracaoOrder',
        'AssociacaoOrder' => 'App\GraphQL\Ordering\AssociacaoOrder',
        'PedidoOrder' => 'App\GraphQL\Ordering\PedidoOrder',
        'CategoriaOrder' => 'App\GraphQL\Ordering\CategoriaOrder',
        'UnidadeOrder' => 'App\GraphQL\Ordering\UnidadeOrder',
        'OrigemOrder' => 'App\GraphQL\Ordering\OrigemOrder',
        'OperacaoOrder' => 'App\GraphQL\Ordering\OperacaoOrder',
        'ImpostoOrder' => 'App\GraphQL\Ordering\ImpostoOrder',
        'TributacaoOrder' => 'App\GraphQL\Ordering\TributacaoOrder',
        'ProdutoOrder' => 'App\GraphQL\Ordering\ProdutoOrder',
        'ServicoOrder' => 'App\GraphQL\Ordering\ServicoOrder',
        'ClassificacaoOrder' => 'App\GraphQL\Ordering\ClassificacaoOrder',
        'ContaOrder' => 'App\GraphQL\Ordering\ContaOrder',
        'MovimentacaoOrder' => 'App\GraphQL\Ordering\MovimentacaoOrder',
        'CreditoOrder' => 'App\GraphQL\Ordering\CreditoOrder',
        'ChequeOrder' => 'App\GraphQL\Ordering\ChequeOrder',
        'PagamentoOrder' => 'App\GraphQL\Ordering\PagamentoOrder',
        'ItemOrder' => 'App\GraphQL\Ordering\ItemOrder',
        'ModuloOrder' => 'App\GraphQL\Ordering\ModuloOrder',
        'FuncionalidadeOrder' => 'App\GraphQL\Ordering\FuncionalidadeOrder',
        'PermissaoOrder' => 'App\GraphQL\Ordering\PermissaoOrder',
        'AuditoriaOrder' => 'App\GraphQL\Ordering\AuditoriaOrder',
        'ComposicaoOrder' => 'App\GraphQL\Ordering\ComposicaoOrder',
        'FornecedorOrder' => 'App\GraphQL\Ordering\FornecedorOrder',
        'ListaOrder' => 'App\GraphQL\Ordering\ListaOrder',
        'CompraOrder' => 'App\GraphQL\Ordering\CompraOrder',
        'RequisitoOrder' => 'App\GraphQL\Ordering\RequisitoOrder',
        'EstoqueOrder' => 'App\GraphQL\Ordering\EstoqueOrder',
        'GrupoOrder' => 'App\GraphQL\Ordering\GrupoOrder',
        'PropriedadeOrder' => 'App\GraphQL\Ordering\PropriedadeOrder',
        'PacoteOrder' => 'App\GraphQL\Ordering\PacoteOrder',
        'DispositivoOrder' => 'App\GraphQL\Ordering\DispositivoOrder',
        'ImpressoraOrder' => 'App\GraphQL\Ordering\ImpressoraOrder',
        'PromocaoOrder' => 'App\GraphQL\Ordering\PromocaoOrder',
        'AcessoOrder' => 'App\GraphQL\Ordering\AcessoOrder',
        'CatalogoOrder' => 'App\GraphQL\Ordering\CatalogoOrder',
        'SistemaOrder' => 'App\GraphQL\Ordering\SistemaOrder',
        'ResumoOrder' => 'App\GraphQL\Ordering\ResumoOrder',
        'FormacaoOrder' => 'App\GraphQL\Ordering\FormacaoOrder',
        'EnderecoOrder' => 'App\GraphQL\Ordering\EnderecoOrder',
        'HorarioOrder' => 'App\GraphQL\Ordering\HorarioOrder',
        'PatrimonioOrder' => 'App\GraphQL\Ordering\PatrimonioOrder',
        'JuncaoOrder' => 'App\GraphQL\Ordering\JuncaoOrder',
        'RegimeOrder' => 'App\GraphQL\Ordering\RegimeOrder',
        'EmitenteOrder' => 'App\GraphQL\Ordering\EmitenteOrder',
        'NotaOrder' => 'App\GraphQL\Ordering\NotaOrder',
        'EventoOrder' => 'App\GraphQL\Ordering\EventoOrder',
        'EmpresaOrder' => 'App\GraphQL\Ordering\EmpresaOrder',
        'PontuacaoOrder' => 'App\GraphQL\Ordering\PontuacaoOrder',
        'TelefoneOrder' => 'App\GraphQL\Ordering\TelefoneOrder',
        'ObservacaoOrder' => 'App\GraphQL\Ordering\ObservacaoOrder',
        'CupomOrder' => 'App\GraphQL\Ordering\CupomOrder',
        'MetricaOrder' => 'App\GraphQL\Ordering\MetricaOrder',
        'AvaliacaoOrder' => 'App\GraphQL\Ordering\AvaliacaoOrder',
        'CozinhaOrder' => 'App\GraphQL\Ordering\CozinhaOrder',
        'CardapioOrder' => 'App\GraphQL\Ordering\CardapioOrder',
        'ContagemOrder' => 'App\GraphQL\Ordering\ContagemOrder',

        'SetorInput' => 'App\GraphQL\Inputs\SetorInput',
        'MesaInput' => 'App\GraphQL\Inputs\MesaInput',
        'SessaoInput' => 'App\GraphQL\Inputs\SessaoInput',
        'BancoInput' => 'App\GraphQL\Inputs\BancoInput',
        'CarteiraInput' => 'App\GraphQL\Inputs\CarteiraInput',
        'CaixaInput' => 'App\GraphQL\Inputs\CaixaInput',
        'FormaInput' => 'App\GraphQL\Inputs\FormaInput',
        'CartaoInput' => 'App\GraphQL\Inputs\CartaoInput',
        'FuncaoInput' => 'App\GraphQL\Inputs\FuncaoInput',
        'ClienteInput' => 'App\GraphQL\Inputs\ClienteInput',
        'PrestadorInput' => 'App\GraphQL\Inputs\PrestadorInput',
        'MoedaInput' => 'App\GraphQL\Inputs\MoedaInput',
        'PaisInput' => 'App\GraphQL\Inputs\PaisInput',
        'EstadoInput' => 'App\GraphQL\Inputs\EstadoInput',
        'CidadeInput' => 'App\GraphQL\Inputs\CidadeInput',
        'BairroInput' => 'App\GraphQL\Inputs\BairroInput',
        'ZonaInput' => 'App\GraphQL\Inputs\ZonaInput',
        'LocalizacaoInput' => 'App\GraphQL\Inputs\LocalizacaoInput',
        'ComandaInput' => 'App\GraphQL\Inputs\ComandaInput',
        'ViagemInput' => 'App\GraphQL\Inputs\ViagemInput',
        'IntegracaoInput' => 'App\GraphQL\Inputs\IntegracaoInput',
        'AssociacaoInput' => 'App\GraphQL\Inputs\AssociacaoInput',
        'PedidoInput' => 'App\GraphQL\Inputs\PedidoInput',
        'CategoriaInput' => 'App\GraphQL\Inputs\CategoriaInput',
        'UnidadeInput' => 'App\GraphQL\Inputs\UnidadeInput',
        'OrigemInput' => 'App\GraphQL\Inputs\OrigemInput',
        'OperacaoInput' => 'App\GraphQL\Inputs\OperacaoInput',
        'ImpostoInput' => 'App\GraphQL\Inputs\ImpostoInput',
        'TributacaoInput' => 'App\GraphQL\Inputs\TributacaoInput',
        'ProdutoInput' => 'App\GraphQL\Inputs\ProdutoInput',
        'ServicoInput' => 'App\GraphQL\Inputs\ServicoInput',
        'ClassificacaoInput' => 'App\GraphQL\Inputs\ClassificacaoInput',
        'ContaInput' => 'App\GraphQL\Inputs\ContaInput',
        'MovimentacaoInput' => 'App\GraphQL\Inputs\MovimentacaoInput',
        'CreditoInput' => 'App\GraphQL\Inputs\CreditoInput',
        'ChequeInput' => 'App\GraphQL\Inputs\ChequeInput',
        'PagamentoInput' => 'App\GraphQL\Inputs\PagamentoInput',
        'ItemInput' => 'App\GraphQL\Inputs\ItemInput',
        'ModuloInput' => 'App\GraphQL\Inputs\ModuloInput',
        'FuncionalidadeInput' => 'App\GraphQL\Inputs\FuncionalidadeInput',
        'PermissaoInput' => 'App\GraphQL\Inputs\PermissaoInput',
        'AuditoriaInput' => 'App\GraphQL\Inputs\AuditoriaInput',
        'ComposicaoInput' => 'App\GraphQL\Inputs\ComposicaoInput',
        'FornecedorInput' => 'App\GraphQL\Inputs\FornecedorInput',
        'ListaInput' => 'App\GraphQL\Inputs\ListaInput',
        'CompraInput' => 'App\GraphQL\Inputs\CompraInput',
        'RequisitoInput' => 'App\GraphQL\Inputs\RequisitoInput',
        'EstoqueInput' => 'App\GraphQL\Inputs\EstoqueInput',
        'GrupoInput' => 'App\GraphQL\Inputs\GrupoInput',
        'PropriedadeInput' => 'App\GraphQL\Inputs\PropriedadeInput',
        'PacoteInput' => 'App\GraphQL\Inputs\PacoteInput',
        'DispositivoInput' => 'App\GraphQL\Inputs\DispositivoInput',
        'ImpressoraInput' => 'App\GraphQL\Inputs\ImpressoraInput',
        'PromocaoInput' => 'App\GraphQL\Inputs\PromocaoInput',
        'AcessoInput' => 'App\GraphQL\Inputs\AcessoInput',
        'CatalogoInput' => 'App\GraphQL\Inputs\CatalogoInput',
        'SistemaInput' => 'App\GraphQL\Inputs\SistemaInput',
        'ResumoInput' => 'App\GraphQL\Inputs\ResumoInput',
        'FormacaoInput' => 'App\GraphQL\Inputs\FormacaoInput',
        'EnderecoInput' => 'App\GraphQL\Inputs\EnderecoInput',
        'HorarioInput' => 'App\GraphQL\Inputs\HorarioInput',
        'PatrimonioInput' => 'App\GraphQL\Inputs\PatrimonioInput',
        'JuncaoInput' => 'App\GraphQL\Inputs\JuncaoInput',
        'RegimeInput' => 'App\GraphQL\Inputs\RegimeInput',
        'EmitenteInput' => 'App\GraphQL\Inputs\EmitenteInput',
        'NotaInput' => 'App\GraphQL\Inputs\NotaInput',
        'EventoInput' => 'App\GraphQL\Inputs\EventoInput',
        'EmpresaInput' => 'App\GraphQL\Inputs\EmpresaInput',
        'PontuacaoInput' => 'App\GraphQL\Inputs\PontuacaoInput',
        'TelefoneInput' => 'App\GraphQL\Inputs\TelefoneInput',
        'ObservacaoInput' => 'App\GraphQL\Inputs\ObservacaoInput',
        'CupomInput' => 'App\GraphQL\Inputs\CupomInput',
        'MetricaInput' => 'App\GraphQL\Inputs\MetricaInput',
        'AvaliacaoInput' => 'App\GraphQL\Inputs\AvaliacaoInput',
        'CozinhaInput' => 'App\GraphQL\Inputs\CozinhaInput',
        'CardapioInput' => 'App\GraphQL\Inputs\CardapioInput',
        'ContagemInput' => 'App\GraphQL\Inputs\ContagemInput',

        'Setor' => 'App\GraphQL\Types\SetorType',
        'Mesa' => 'App\GraphQL\Types\MesaType',
        'Sessao' => 'App\GraphQL\Types\SessaoType',
        'Banco' => 'App\GraphQL\Types\BancoType',
        'Carteira' => 'App\GraphQL\Types\CarteiraType',
        'Caixa' => 'App\GraphQL\Types\CaixaType',
        'Forma' => 'App\GraphQL\Types\FormaType',
        'Cartao' => 'App\GraphQL\Types\CartaoType',
        'Funcao' => 'App\GraphQL\Types\FuncaoType',
        'Cliente' => 'App\GraphQL\Types\ClienteType',
        'Prestador' => 'App\GraphQL\Types\PrestadorType',
        'Moeda' => 'App\GraphQL\Types\MoedaType',
        'Pais' => 'App\GraphQL\Types\PaisType',
        'Estado' => 'App\GraphQL\Types\EstadoType',
        'Cidade' => 'App\GraphQL\Types\CidadeType',
        'Bairro' => 'App\GraphQL\Types\BairroType',
        'Zona' => 'App\GraphQL\Types\ZonaType',
        'Localizacao' => 'App\GraphQL\Types\LocalizacaoType',
        'Comanda' => 'App\GraphQL\Types\ComandaType',
        'Viagem' => 'App\GraphQL\Types\ViagemType',
        'Integracao' => 'App\GraphQL\Types\IntegracaoType',
        'Associacao' => 'App\GraphQL\Types\AssociacaoType',
        'Pedido' => 'App\GraphQL\Types\PedidoType',
        'Categoria' => 'App\GraphQL\Types\CategoriaType',
        'Unidade' => 'App\GraphQL\Types\UnidadeType',
        'Origem' => 'App\GraphQL\Types\OrigemType',
        'Operacao' => 'App\GraphQL\Types\OperacaoType',
        'Imposto' => 'App\GraphQL\Types\ImpostoType',
        'Tributacao' => 'App\GraphQL\Types\TributacaoType',
        'Produto' => 'App\GraphQL\Types\ProdutoType',
        'Servico' => 'App\GraphQL\Types\ServicoType',
        'Classificacao' => 'App\GraphQL\Types\ClassificacaoType',
        'Conta' => 'App\GraphQL\Types\ContaType',
        'Movimentacao' => 'App\GraphQL\Types\MovimentacaoType',
        'Credito' => 'App\GraphQL\Types\CreditoType',
        'Cheque' => 'App\GraphQL\Types\ChequeType',
        'Pagamento' => 'App\GraphQL\Types\PagamentoType',
        'Item' => 'App\GraphQL\Types\ItemType',
        'Modulo' => 'App\GraphQL\Types\ModuloType',
        'Funcionalidade' => 'App\GraphQL\Types\FuncionalidadeType',
        'Permissao' => 'App\GraphQL\Types\PermissaoType',
        'Auditoria' => 'App\GraphQL\Types\AuditoriaType',
        'Composicao' => 'App\GraphQL\Types\ComposicaoType',
        'Fornecedor' => 'App\GraphQL\Types\FornecedorType',
        'Lista' => 'App\GraphQL\Types\ListaType',
        'Compra' => 'App\GraphQL\Types\CompraType',
        'Requisito' => 'App\GraphQL\Types\RequisitoType',
        'Estoque' => 'App\GraphQL\Types\EstoqueType',
        'Grupo' => 'App\GraphQL\Types\GrupoType',
        'Propriedade' => 'App\GraphQL\Types\PropriedadeType',
        'Pacote' => 'App\GraphQL\Types\PacoteType',
        'Dispositivo' => 'App\GraphQL\Types\DispositivoType',
        'Impressora' => 'App\GraphQL\Types\ImpressoraType',
        'Promocao' => 'App\GraphQL\Types\PromocaoType',
        'Acesso' => 'App\GraphQL\Types\AcessoType',
        'Catalogo' => 'App\GraphQL\Types\CatalogoType',
        'Sistema' => 'App\GraphQL\Types\SistemaType',
        'Resumo' => 'App\GraphQL\Types\ResumoType',
        'Formacao' => 'App\GraphQL\Types\FormacaoType',
        'Endereco' => 'App\GraphQL\Types\EnderecoType',
        'Horario' => 'App\GraphQL\Types\HorarioType',
        'Patrimonio' => 'App\GraphQL\Types\PatrimonioType',
        'Juncao' => 'App\GraphQL\Types\JuncaoType',
        'Regime' => 'App\GraphQL\Types\RegimeType',
        'Emitente' => 'App\GraphQL\Types\EmitenteType',
        'Nota' => 'App\GraphQL\Types\NotaType',
        'Evento' => 'App\GraphQL\Types\EventoType',
        'Empresa' => 'App\GraphQL\Types\EmpresaType',
        'Pontuacao' => 'App\GraphQL\Types\PontuacaoType',
        'Telefone' => 'App\GraphQL\Types\TelefoneType',
        'Observacao' => 'App\GraphQL\Types\ObservacaoType',
        'Cupom' => 'App\GraphQL\Types\CupomType',
        'Metrica' => 'App\GraphQL\Types\MetricaType',
        'Avaliacao' => 'App\GraphQL\Types\AvaliacaoType',
        'Cozinha' => 'App\GraphQL\Types\CozinhaType',
        'Cardapio' => 'App\GraphQL\Types\CardapioType',
        'Contagem' => 'App\GraphQL\Types\ContagemType',

        'CarteiraTipo' => 'App\GraphQL\Enums\CarteiraTipoEnum',
        'CarteiraAmbiente' => 'App\GraphQL\Enums\CarteiraAmbienteEnum',
        'FormaTipo' => 'App\GraphQL\Enums\FormaTipoEnum',
        'ClienteTipo' => 'App\GraphQL\Enums\ClienteTipoEnum',
        'ClienteGenero' => 'App\GraphQL\Enums\ClienteGeneroEnum',
        'ClienteStatus' => 'App\GraphQL\Enums\ClienteStatusEnum',
        'PrestadorVinculo' => 'App\GraphQL\Enums\PrestadorVinculoEnum',
        'LocalizacaoTipo' => 'App\GraphQL\Enums\LocalizacaoTipoEnum',
        'AssociacaoStatus' => 'App\GraphQL\Enums\AssociacaoStatusEnum',
        'PedidoTipo' => 'App\GraphQL\Enums\PedidoTipoEnum',
        'PedidoEstado' => 'App\GraphQL\Enums\PedidoEstadoEnum',
        'ImpostoGrupo' => 'App\GraphQL\Enums\ImpostoGrupoEnum',
        'ProdutoTipo' => 'App\GraphQL\Enums\ProdutoTipoEnum',
        'ServicoTipo' => 'App\GraphQL\Enums\ServicoTipoEnum',
        'ContaTipo' => 'App\GraphQL\Enums\ContaTipoEnum',
        'ContaFonte' => 'App\GraphQL\Enums\ContaFonteEnum',
        'ContaModo' => 'App\GraphQL\Enums\ContaModoEnum',
        'ContaFormula' => 'App\GraphQL\Enums\ContaFormulaEnum',
        'ContaEstado' => 'App\GraphQL\Enums\ContaEstadoEnum',
        'PagamentoEstado' => 'App\GraphQL\Enums\PagamentoEstadoEnum',
        'ItemEstado' => 'App\GraphQL\Enums\ItemEstadoEnum',
        'AuditoriaTipo' => 'App\GraphQL\Enums\AuditoriaTipoEnum',
        'AuditoriaPrioridade' => 'App\GraphQL\Enums\AuditoriaPrioridadeEnum',
        'ComposicaoTipo' => 'App\GraphQL\Enums\ComposicaoTipoEnum',
        'ListaEstado' => 'App\GraphQL\Enums\ListaEstadoEnum',
        'GrupoTipo' => 'App\GraphQL\Enums\GrupoTipoEnum',
        'GrupoFuncao' => 'App\GraphQL\Enums\GrupoFuncaoEnum',
        'DispositivoTipo' => 'App\GraphQL\Enums\DispositivoTipoEnum',
        'ImpressoraModo' => 'App\GraphQL\Enums\ImpressoraModoEnum',
        'PromocaoLocal' => 'App\GraphQL\Enums\PromocaoLocalEnum',
        'PromocaoFuncaoVendas' => 'App\GraphQL\Enums\PromocaoFuncaoVendasEnum',
        'PromocaoFuncaoCliente' => 'App\GraphQL\Enums\PromocaoFuncaoClienteEnum',
        'HorarioModo' => 'App\GraphQL\Enums\HorarioModoEnum',
        'PatrimonioEstado' => 'App\GraphQL\Enums\PatrimonioEstadoEnum',
        'JuncaoEstado' => 'App\GraphQL\Enums\JuncaoEstadoEnum',
        'EmitenteAmbiente' => 'App\GraphQL\Enums\EmitenteAmbienteEnum',
        'NotaTipo' => 'App\GraphQL\Enums\NotaTipoEnum',
        'NotaAmbiente' => 'App\GraphQL\Enums\NotaAmbienteEnum',
        'NotaAcao' => 'App\GraphQL\Enums\NotaAcaoEnum',
        'NotaEstado' => 'App\GraphQL\Enums\NotaEstadoEnum',
        'EventoEstado' => 'App\GraphQL\Enums\EventoEstadoEnum',
        'CupomTipoDesconto' => 'App\GraphQL\Enums\CupomTipoDescontoEnum',
        'CupomFuncaoPedidos' => 'App\GraphQL\Enums\CupomFuncaoPedidosEnum',
        'CupomFuncaoValor' => 'App\GraphQL\Enums\CupomFuncaoValorEnum',
        'MetricaTipo' => 'App\GraphQL\Enums\MetricaTipoEnum',
        'CardapioLocal' => 'App\GraphQL\Enums\CardapioLocalEnum',
    ],

    // The types will be loaded on demand. Default is to load all types on each request
    // Can increase performance on schemes with many types
    // Presupposes the config type key to match the type class name property
    'lazyload_types' => false,

    // This callable will be passed the Error object for each errors GraphQL catch.
    // The method should return an array representing the error.
    // Typically:
    // [
    //     'message' => '',
    //     'locations' => []
    // ]
    'error_formatter' => ['\Rebing\GraphQL\GraphQL', 'formatError'],

    /*
     * Custom Error Handling
     *
     * Expected handler signature is: function (array $errors, callable $formatter): array
     *
     * The default handler will pass exceptions to laravel Error Handling mechanism
     */
    'errors_handler' => ['\Rebing\GraphQL\GraphQL', 'handleErrors'],

    // You can set the key, which will be used to retrieve the dynamic variables
    'params_key'    => 'variables',

    /*
     * Options to limit the query complexity and depth. See the doc
     * @ https://github.com/webonyx/graphql-php#security
     * for details. Disabled by default.
     */
    'security' => [
        'query_max_complexity'  => null,
        'query_max_depth'       => null,
        'disable_introspection' => false,
    ],

    /*
     * You can define your own pagination type.
     * Reference \Rebing\GraphQL\Support\PaginationType::class
     */
    'pagination_type' => \Rebing\GraphQL\Support\PaginationType::class,

    /*
     * Config for GraphiQL (see (https://github.com/graphql/graphiql).
     */
    'graphiql' => [
        'prefix'     => '/graphiql',
        'controller' => \Rebing\GraphQL\GraphQLController::class.'@graphiql',
        'middleware' => [],
        'view'       => 'graphql::graphiql',
        'display'    => env('ENABLE_GRAPHIQL', true),
    ],

    /*
     * Overrides the default field resolver
     * See http://webonyx.github.io/graphql-php/data-fetching/#default-field-resolver
     *
     * Example:
     *
     * ```php
     * 'defaultFieldResolver' => function ($root, $args, $context, $info) {
     * },
     * ```
     * or
     * ```php
     * 'defaultFieldResolver' => [SomeKlass::class, 'someMethod'],
     * ```
     */
    'defaultFieldResolver' => null,

    /*
     * Any headers that will be added to the response returned by the default controller
     */
    'headers' => [],

    /*
     * Any JSON encoding options when returning a response from the default controller
     * See http://php.net/manual/function.json-encode.php for the full list of options
     */
    'json_encoding_options' => 0,
];
