#!/bin/bash

perl -0777 -i.original -pe "s/USE `GrandChef`\$\$\n//igs" ../database/model/script.sql
perl -0777 -i.original -pe "s/USE `GrandChef`;\n//igs" ../database/model/script.sql
perl -0777 -i.original -pe "s/END\$\$\n/END \$\$/igs" ../database/model/script.sql
perl -0777 -i.original -pe "s/`GrandChef`\.//igs" ../database/model/script.sql
rm -f ../database/model/script.sql.original
cp -f ../database/model/script.sql ../storage/db/dumps/script_no_trigger.sql
perl -0777 -i.original -pe "s/\nDELIMITER \$\$.*?DELIMITER ;\n\n//igs" ../storage/db/dumps/script_no_trigger.sql
perl -0777 -i.original -pe "s/' \/\* comment truncated \*\/ \/\*([^\*]+)\*\//$1'/igs" ../storage/db/dumps/script_no_trigger.sql
perl -0777 -i.original -pe "s/([^\\\][\\\])([^\\\'])/$1\\\$2/igs" ../storage/db/dumps/script_no_trigger.sql
rm -f ../storage/db/dumps/script_no_trigger.sql.original
